Repository ita-social-projects/StreetCode_Client, pull requests merged in 2023-11, with the labels that each got.

#971 395 donates incorrect input
  src/app/common/components/modals/Donates/DonatesModal.component.tsx
  src/app/common/components/modals/Donates/DonatesModal.styles.scss
  src/features/AdditionalPages/SupportUsPage/components/DonationBlock.component.tsx
  src/features/AdditionalPages/SupportUsPage/components/DonationBlock.styles.scss
Labels: bug

#978 Add notification in the partners' email field
  src/app/common/components/ContactForm/ContactForm.component.tsx
  src/app/common/components/ContactForm/ContactForm.styles.scss
  src/app/common/components/modals/Partners/PartnersModal.component.tsx
  src/app/common/components/modals/Partners/PartnersModal.styles.scss
  src/app/router/Routes.tsx
Labels: bug

#981 Fixed styles for streetcode slider in tablet and mobile mode
  src/features/MainPage/StreetcodeSlider/StreetcodeSliderItem/StreetcodeSliderItem.styles.scss
Labels: bug, styles

#985 AR new text
  src/features/StreetcodePage/QRBlock/QR.component.tsx
  src/features/StreetcodePage/QRBlock/QRMobile/QRMobile.component.tsx
Labels: bug

#991 fix news button overflowing
  src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.styles.scss
Labels: small

#994 Fixed loading of fans modal categories
  src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx
  src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansBlock.component.tsx
  src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
Labels: bug, admin-page

#995 Modal button disable
  src/app/common/components/ContactForm/ContactForm.component.tsx
  src/app/common/components/modals/ContactUsModal/ContactUsModal.component.tsx
  src/features/AdminPage/ForFansPage/ForFansPage/CategoryAdminModal.component.tsx
  src/features/AdminPage/NewStreetcode/InterestingFactsBlock/FactsAdminModal/InterestingFactsAdminModal.component.tsx
  src/features/AdminPage/PartnersPage/PartnerModal/PartnerModal.component.tsx
  src/features/AdminPage/TeamPage/TeamModal/TeamModal.component.tsx
Labels: admin-page

#1003 fix not fetching streetcode on streetcode catalog page
  src/features/StreetcodeCatalogPage/StreetcodeCatalogItem/StreetcodeCatalogItem.component.tsx
Labels: bug

#1005 Now progress bar is visible from 1448px to 1025px
  src/features/ProgressBar/ProgressBar.styles.scss
Labels: bug, styles

#987 Add filter instead of gif
  src/app/common/components/FileUploader/FileUploader.component.tsx
  src/features/AdminPage/NewStreetcode/MainBlock/FileInputsPart.component.tsx
  src/features/AdminPage/NewStreetcode/MainBlock/PreviewFileModal/PreviewFileModal.component.tsx
  src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx
  src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.styles.scss
Labels: small

#1026 Fix issue 847. Fix StreetCode Url Reference
  src/features/AdditionalPages/PrivatePolicyPage/Title/Title.component.tsx
Labels: bug

#1027 Fix Sources Styles issue 842
  src/features/StreetcodePage/SourcesBlock/Sources.styles.scss
Labels: bug
