Repository ita-social-projects/StreetCode_Client, pull requests merged in 2023-06, with the labels that each got.

#348 fixed some corrections
  src/app/api/streetcode/text-content/terms.api.ts
  src/app/common/components/modals/Terms/AddTerm/AddTermModal.component.tsx
  src/app/layout/footer/Footer.component.tsx
  src/app/stores/term-store.ts
  src/assets/sass/variables/_variables.colors.scss
  src/features/AdminPage/NewStreetcode/TimelineBlock/NewTimelineModal/NewTimelineModal.component.tsx
  src/features/AdminPage/TermDictionary/TermDictionary.component.tsx
  src/features/AdminPage/TermDictionary/TermDictionary.styles.scss
  src/features/MainPage/NewsSlider/NewsSlider.component.tsx
  src/features/MainPage/StreetcodeSlider/StreetcodeSlider.component.tsx
  src/features/MainPage/TeamSlider/TeamComponent.component.tsx
  src/features/StreetcodeCatalogPage/StreetcodeCatalogItem/StreetcodeCatalogItem.styles.scss
  src/models/timeline/chronology.model.ts
Labels: bug

#337 Fix popup image
  src/features/AdditionalPages/PartnersPage/PartnersBlock/PartnersBlock.component.tsx
  src/features/StreetcodePage/Streetcode.component.tsx
Labels: bug

#346 Now parser removes <p> around related term and there is no new line b…
  src/features/StreetcodePage/TextBlock/SearchTerms/SearchTerms.component.tsx
Labels: bug

#358 Cleared error related with render
  src/features/AdminPage/StreetcodesTable/StreetcodesTable.component.tsx
Labels: bug

#363 Main heading adaptive
  src/assets/images/main-page/headerRectMobile.svg
  src/features/MainPage/Heading/Heading.component.tsx
  src/features/MainPage/Heading/Heading.styles.scss
Labels: enhancement

#362 Sources slider items fix
  src/features/StreetcodePage/SourcesBlock/Sources.component.tsx
  src/features/StreetcodePage/SourcesBlock/Sources.styles.scss
Labels: bug, enhancement

#361 Donates page underline and buttons logic fix
  src/features/AdditionalPages/SupportUsPage/components/DonationBlock.component.tsx
  src/features/AdditionalPages/SupportUsPage/components/DonationBlock.styles.scss
Labels: styles

#369 Fixed bug related with image creation
  src/features/AdminPage/NewsPage/NewsModal/NewsModal.component.tsx
Labels: bug

#382 [Enhancement] Google analytics addition
  src/app/common/components/modals/HeaderLogin/HeaderLoginModal.component.tsx
  src/app/common/utils/googleAnalytics.unility.tsx
  src/app/layout/header/HeaderBlock.component.tsx
  src/features/AdditionalPages/NewsPage/News.component.tsx
  src/features/AdditionalPages/SupportUsPage/SupportUs.component.tsx
  src/features/AdditionalPages/SupportUsPage/components/DonationBlock.component.tsx
  src/features/MainPage/InstagramBlock/InstagramSliderItem/InstagramSliderItem.component.tsx
  src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.component.tsx
  src/features/MainPage/StreetcodeSlider/StreetcodeSliderItem/StreetcodeSliderItem.component.tsx
  src/features/StreetcodeCatalogPage/StreetcodeCatalogItem/StreetcodeCatalogItem.component.tsx
  src/features/StreetcodePage/QRBlock/QRMobile/QRMobile.component.tsx
Labels: enhancement

#372 Info tag popup plus fixes
  src/app/stores/facts-store.ts
  src/app/stores/partners-store.ts
  src/app/stores/related-terms-store.ts
  src/app/stores/sources-store.ts
  src/app/stores/streetcode-art-store.ts
  src/app/stores/streetcode-coordinates-store.ts
  src/app/stores/timeline-store.ts
  src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.component.tsx
  src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.style.scss
  src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx
Labels: bug, enhancement

#384 Fix RF cards' tags
  src/app/common/components/modals/Tags/TagsSliderModal/TagsSliderModal.component.tsx
  src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.component.tsx
  src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.styles.scss
Labels: enhancement, styles

#376 fixed situation when image was bigger then text and page just broke, and fixed paddings on mobile
  src/features/AdditionalPages/NewsPage/News.component.tsx
  src/features/AdditionalPages/NewsPage/News.styles.scss
Labels: bug

#393 Fix RF tag modal.
  src/app/stores/streetcodes-bytag-store.ts
Labels: bug

#405 Added validation to terms
  src/app/common/components/modals/Terms/AddTerm/AddTermModal.component.tsx
  src/app/common/components/modals/Terms/DeleteTerm/DeleteTermModal.component.tsx
  src/app/common/components/modals/Terms/EditTerm/EditTermModal.component.tsx
  src/features/AdminPage/TermDictionary/TermDictionary.component.tsx
Labels: bug, enhancement

#409 Changed spacing between QRBlock and sources
  src/features/StreetcodePage/QRBlock/QR.styles.scss
Labels: styles

#421 remove image, only send image id
  src/features/AdminPage/NewStreetcode/ArtGallery/components/Download.component.tsx
  src/features/AdminPage/NewStreetcode/InterestingFactsBlock/FactsAdminModal/InterestingFactsAdminModal.component.tsx
  src/features/AdminPage/NewStreetcode/MainBlock/FileInputsPart.component.tsx
  src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
  src/models/media/art.model.ts
  src/models/media/image.model.ts
  src/models/streetcode/streetcode-types.model.ts
Labels: bug

#425 [Fix/419]Fix art modal window input fields
  src/features/AdminPage/NewStreetcode/ArtGallery/components/Download.component.tsx
  src/features/AdminPage/NewStreetcode/ArtGallery/components/PreviewImageModal/PreviewImageModal.component.tsx
Labels: bug, duplicate
