Repository ita-social-projects/StreetCode_Client, pull requests merged in 2023-09, with the labels that each got.

#734 Changed long dash (—) to Word standard dash (–)
  src/features/AdminPage/NewStreetcode/MainBlock/DatePickerPart.component.tsx
Labels: bug

#724 Fixed text displaying in source modal
  src/app/common/components/modals/Sources/SourcesModal.styles.scss
Labels: bug, styles

#716 AR block centered on modile
  src/features/StreetcodePage/QRBlock/QRMobile/QRMobile.styles.scss
Labels: bug, styles

#735 Vlad month chronologi format fix
  src/features/StreetcodePage/TimelineBlock/TimelineItem/TimelineItem.component.tsx
Labels: bug

#736 Fixed news url displaying
  src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.component.tsx
Labels: bug

#737 Allow webp format files to upload
  src/app/common/components/modals/InterestingFacts/FactsAdminModal/InterestingFactsAdminModal.component.tsx
  src/features/AdminPage/ForFansPage/ForFansPage/CategoryAdminModal.component.tsx
  src/features/AdminPage/NewStreetcode/ArtGallery/components/Download.component.tsx
  src/features/AdminPage/NewStreetcode/InterestingFactsBlock/FactsAdminModal/InterestingFactsAdminModal.component.tsx
  src/features/AdminPage/NewStreetcode/MainBlock/FileInputsPart.component.tsx
  src/features/AdminPage/NewsPage/NewsModal/NewsModal.component.tsx
  src/features/AdminPage/PartnersPage/PartnerModal/PartnerModal.component.tsx
  src/features/AdminPage/TeamPage/TeamModal/TeamModal.component.tsx
Labels: enhancement

#738 Fixed wow-facts img description displaying
  src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.component.tsx
  src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.component.tsx
Labels: bug

#739 deleting requared rule to video filed
  src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/LinkEditor.component.tsx
Labels: bug

#741 Partners admin
  src/features/AdminPage/NewStreetcode/PartnerBlock/PartnerBlockAdmin.components.tsx
Labels: enhancement

#730 third attempt to fix main-text
  package.json
  src/features/StreetcodePage/TextBlock/ReadMore/ReadMore.component.tsx
  src/features/StreetcodePage/TextBlock/ReadMore/ReadMore.styles.scss
Labels: wontfix

#748 border delete for sliders
  src/features/AboutUsPage/TeamMembers/TeamMembers.component.scss
  src/features/AboutUsPage/TeamMembers/TeamMembersList/TeamMemberList.styles.scss
  src/features/AboutUsPage/TeamMembers/TeamPositionsSlider/TeamMembersSlider.component.tsx
Labels: bug

#750 fixed modal
  src/features/AdminPage/JobsPage/JobsModal/JobsModal.component.tsx
Labels: bug

#743 Minor change of burger menu logic
  src/app/layout/header/HeaderDrawer/HeaderDrawer.component.tsx
Labels: bug, enhancement

#746 Fixed numering for ol ul
  src/app/common/components/modals/Sources/SourcesModal.styles.scss
  src/features/AdditionalPages/NewsPage/News.styles.scss
Labels: bug

#747 Change loading sunshine icon in catalog
  src/app/stores/streetcodes-catalog-store.ts
  src/features/StreetcodeCatalogPage/StreetcodeCatalog.component.tsx
Labels: bug

#749 Image moved to right for wide screens and date added by Mariia Padalka
  src/features/AdditionalPages/NewsPage/News.component.tsx
  src/features/AdditionalPages/NewsPage/News.styles.scss
  src/features/AdditionalPages/NewsPage/RandomNewsBlock.component.tsx
Labels: styles

#753 Fixed partners slider scroll
  src/features/StreetcodePage/PartnersBlock/Partners.component.tsx
Labels: bug

#756 Make handling email message sending response
  src/app/common/components/modals/Partners/PartnersModal.component.tsx
  src/features/AdditionalPages/ContactUsPage/MainBlock/ContactForm/ContactForm.component.tsx
  src/index.scss
Labels: bug, enhancement

#744 Fix extra requests on main page
  public/index.html
  src/features/AdditionalPages/PartnersPage/PartnersBlock/PartnersBlock.component.tsx
  src/features/MainPage/MainPage.component.tsx
  src/features/MainPage/NewsSlider/NewsSlider.component.tsx
  src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.component.tsx
  src/features/MainPage/StreetcodeSlider/StreetcodeSlider.component.tsx
  src/features/MainPage/StreetcodeSlider/StreetcodeSliderItem/StreetcodeSliderItem.component.tsx
  src/features/MainPage/TeamSlider/TeamComponent.component.tsx
  src/features/MainPage/TeamSlider/TeamItemSlider/TeamItemSlider.component.tsx
Labels: bug

#752 Feature after modal adding
  src/app/common/components/modals/Terms/AddTerm/AddTermModal.component.tsx
  src/features/AdminPage/ForFansPage/ForFansPage/CategoryAdminModal.component.tsx
  src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx
  src/features/AdminPage/NewStreetcode/InterestingFactsBlock/FactsAdminModal/InterestingFactsAdminModal.component.tsx
  src/features/AdminPage/NewStreetcode/TimelineBlock/NewTimelineModal/NewTimelineModal.component.tsx
  src/features/AdminPage/NewsPage/NewsModal/NewsModal.component.tsx
  src/features/AdminPage/PartnersPage/PartnerModal/PartnerModal.component.tsx
  src/features/AdminPage/TeamPage/TeamModal/TeamModal.component.tsx
Labels: enhancement

#768 Incorrect aspect ratio at 1200 screen size
  src/features/MainPage/TopCarousel/TopCarousel.styles.scss
Labels: bug

#740 Allow multiple file uploads in art gallery
  src/app/common/components/FileUploader/FileUploader.component.tsx
  src/features/AdminPage/ForFansPage/ForFansPage/CategoryAdminModal.component.tsx
  src/features/AdminPage/NewStreetcode/ArtGallery/components/Download.component.tsx
Labels: small

#772 fix unnessary grey filter for streetcode animation
  src/features/AdminPage/ForFansPage/ForFansPage/CategoryAdminModal.component.tsx
  src/features/AdminPage/NewStreetcode/MainBlock/PreviewFileModal/PreviewFileModal.component.tsx
Labels: bug

#774 - fix swiper navigation on mobile
  src/features/AboutUsPage/TeamMembers/TeamMembers.component.scss
  src/features/AboutUsPage/TeamMembers/TeamPositionsSlider/TeamPostionSlider.component.tsx
  src/features/AboutUsPage/Vacancies/Vacancies.component.tsx
  src/features/AboutUsPage/Vacancies/Vacancies.styles.scss
  src/features/AboutUsPage/Vacancies/Vacancy/Vacancy.syles.scss
Labels: small

#773 Fix design streetcode page
  src/app/common/components/modals/Tags/TagsModal.styles.scss
  src/app/common/components/modals/Tags/TagsSliderModal/TagsSliderModal.styles.scss
  src/features/StreetcodePage/HeadingBlock/BlockHeading.styles.scss
  src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.styles.scss
  src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.styles.scss
  src/features/StreetcodePage/MainBlock/MainBlock.styles.scss
  src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.styles.scss
  src/features/StreetcodePage/MapBlock/CheckBox/CheckBox.styles.scss
  src/features/StreetcodePage/MapBlock/MapBlock.styles.scss
  src/features/StreetcodePage/SourcesBlock/SourceItem/SourceItem.styles.scss
  src/features/StreetcodePage/SourcesBlock/Sources.styles.scss
  src/features/StreetcodePage/Streetcode.styles.scss
  src/features/StreetcodePage/TextBlock/ReadMore/ReadMore.styles.scss
  src/features/StreetcodePage/TextBlock/TextBlock.styles.scss
  src/features/StreetcodePage/TimelineBlock/TimelineBlock.styles.scss
  src/features/StreetcodePage/TimelineBlock/TimelineItem/TimelineItem.styles.scss
  src/features/StreetcodePage/TimelineBlock/TimelineSwiper/TimelineSwiper.styles.scss
Labels: styles

#790 Audio fix
  src/app/api/streetcode/streetcodes.api.ts
  src/features/AdminPage/NewStreetcode/MainBlock/FileInputsPart.component.tsx
  src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
  src/models/media/audio.model.ts
  src/models/streetcode/streetcode-types.model.ts
Labels: bug

#807 tabs on streetcode page fixed
  src/app/common/components/TagList/TagList.styles.scss
  src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx
  src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.styles.scss
Labels: styles

#806 Chronology dates before 1 may 1984 fix
  src/features/AdminPage/NewStreetcode/TimelineBlock/NewTimelineModal/NewTimelineModal.component.tsx
Labels: bug

#805 Displays categories in the category list valerii
  src/features/AdminPage/ForFansPage/ForFansMainPage.component.tsx
  src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx
Labels: bug

#803 Fix partners background
  src/features/AdditionalPages/PartnersPage/Partners.styles.scss
Labels: bug

#797 Fix space between related figure items in a column
  src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigures.component.tsx
  src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigures.styles.scss
Labels: bug

#817 Fix two- and three-element wow facts carousel image title on even num…
  src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.component.tsx
Labels: bug

#781 Streetcode's tags indexation on create and on update
  src/features/AdminPage/NewStreetcode/MainBlock/DragableTags/DragableTags.component.tsx
  src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.component.tsx
  src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
Labels: bug

#818 News major fix
  src/app/common/components/modals/Sources/SourcesModal.styles.scss
  src/features/AdditionalPages/NewsPage/News.styles.scss
  src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.styles.scss
Labels: bug, styles

#800 Make animation field non-required and fix associated code
  src/features/AdminPage/Analytics/Analytics.component.tsx
  src/features/AdminPage/NewStreetcode/MainBlock/FileInputsPart.component.tsx
  src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx
Labels: enhancement

#834 remove dots from teaser
  src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx
Labels: small

#833 Change "join the team" button and open new Vacancies
  package.json
  src/app/common/components/modals/HeaderLogin/HeaderLoginModal.component.tsx
  src/app/common/utils/window.utility.tsx
  src/app/layout/footer/Footer.component.tsx
  src/app/router/Routes.tsx
  src/features/AboutUsPage/AboutUsPage.component.tsx
  src/features/AboutUsPage/TeamMembers/TeamMembers.component.tsx
  src/features/AboutUsPage/Vacancies/Vacancies.component.tsx
  src/features/AboutUsPage/Vacancies/Vacancy/Vacancy.component.tsx
  yarn.lock
Labels: bug

#836 delete unneeded moveble line
  src/features/AboutUsPage/AboutUsPage.component.tsx
Labels: small

#838 fix loader and remove scrollbar when loading
  src/features/StreetcodePage/Streetcode.component.tsx
  src/features/StreetcodePage/Streetcode.styles.scss
Labels: bug, small

#843 forFansCenterTitle: fix title in for fans block, center text
  src/features/AdminPage/ForFansPage/ForFansPage/CategoryAdminModal.component.tsx
  src/features/StreetcodePage/SourcesBlock/SourceItem/SourceItem.styles.scss
Labels: bug

#862 fix problem with text, that is not showed in main text and authorship
  src/features/AdminPage/NewStreetcode/TextBlock/TextBlock.component.tsx
  src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/TextEditor.component.tsx
Labels: bug, small
