Repository ita-social-projects/StreetCode_Client, pull requests merged in 2023-08, with the labels that each got.

#574 Add header block
  src/app/layout/app/App.styles.scss
  src/features/AboutUsPage/AboutUsHeaderText/AboutUsHeaderText.component.tsx
  src/features/AboutUsPage/AboutUsHeaderText/AboutUsHeaderText.styles.scss
  src/features/AboutUsPage/AboutUsPage.component.tsx
  src/features/AboutUsPage/AboutUsPage.styles.scss
Labels: enhancement

#572 Fixed gray square with the year shift
  src/features/StreetcodePage/TimelineBlock/TimelineSwiper/TimelineSwiper.styles.scss
Labels: bug

#573 Fixed and redesigned progress bar
  src/features/ProgressBar/NavigableBlockWrapper.component.tsx
  src/features/ProgressBar/ProgressBar.component.tsx
  src/features/ProgressBar/ProgressBar.styles.scss
  src/features/ProgressBar/ProgressBarFill/ProgressBarFill.styles.scss
  src/features/StreetcodePage/ArtGalleryBlock/ArtGalleryBlock.component.tsx
  src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigures.styles.scss
Labels: bug

#571 [Admin] System allows saving changes StreetCode without filling in 'Анімація' fields
  src/features/AdminPage/NewStreetcode/MainBlock/FileInputsPart.component.tsx
  src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.component.tsx
  src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
Labels: bug

#583 Fix displaying "грудень" in datepicker field on admin panel
  src/features/AdminPage/NewStreetcode/MainBlock/DatePickerPart.component.tsx
Labels: bug

#584 Fixed wow fact photo display
  src/app/common/components/modals/InterestingFacts/InterestingFactsModal.styles.scss
Labels: bug, styles

#588 fix for slider for for fans block
  src/features/StreetcodePage/SourcesBlock/Sources.component.tsx
Labels: bug

#592 added autoclear for appropriate Maps.
  src/app/stores/facts-store.ts
  src/app/stores/image-store.ts
  src/app/stores/news-store.ts
  src/app/stores/sourceadmin-store.ts
Labels: duplicate

#593 Fixed display of non-existent link
  src/features/StreetcodePage/PartnersBlock/PartnerItem/PartnerContent/PartnerContent.component.tsx
Labels: bug

#580 Feature modals change
  src/app/common/components/modals/Terms/AddTerm/AddTermModal.component.tsx
  src/app/common/components/modals/Terms/AddTerm/AddTermModal.styles.scss
  src/app/common/components/modals/Terms/DeleteTerm/DeleteTermModal.styles.scss
  src/app/common/components/modals/Terms/EditTerm/EditTermModal.styles.scss
  src/app/layout/footer/Footer.component.tsx
  src/app/layout/header/HeaderDrawer/SocialMediaLinks/SocialMediaLinks.component.tsx
  src/features/AdditionalPages/ContactUsPage/MainBlock/ContactBlock/ContactBlock.component.tsx
  src/features/AdminPage/AdminModal.styles.scss
  src/features/AdminPage/ForFansPage/ForFansPage/CategoryAdminModal.component.tsx
  src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx
  src/features/AdminPage/NewStreetcode/InterestingFactsBlock/FactsAdminModal/InterestingFactsAdminModal.component.tsx
  src/features/AdminPage/NewStreetcode/TimelineBlock/NewTimelineModal/NewTimelineModal.component.tsx
  src/features/AdminPage/NewsPage/NewsModal/NewsModal.component.tsx
  src/features/AdminPage/PartnersPage/PartnerModal/PartnerModal.component.tsx
  src/features/AdminPage/TeamPage/TeamModal/TeamModal.component.tsx
Labels: enhancement

#597 added modal for admin pannel to add and update vacancy
  src/app/api/job/Job.api.ts
  src/app/common/constants/api-routes.constants.ts
  src/features/AdminPage/JobsPage/JobsModal/JobsModal.component.tsx
  src/features/AdminPage/JobsPage/JobsModal/JobsModal.styles.scss
  src/features/AdminPage/JobsPage/JobsTable/JobsTable.component.tsx
  src/models/jobs/Jobs.model.tsx
Labels: enhancement

#602 stash modal data
  src/features/AdminPage/JobsPage/JobsModal/JobsModal.component.tsx
Labels: enhancement

#604 Fixed preview of animation/b&w
  src/features/AdminPage/NewStreetcode/MainBlock/PreviewFileModal/PreviewFileModal.component.tsx
Labels: bug

#609 fix
  src/features/StreetcodePage/TextBlock/TextBlock.styles.scss
Labels: styles

#596 Vlad sreetcodes adaptive fix
  src/features/StreetcodeCatalogPage/StreetcodeCatalogItem/StreetcodeCatalogItem.styles.scss
Labels: bug, styles

#600 Made the modal not clickable on the phone version
  src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.component.tsx
Labels: bug

#601 Made non-actiive sretcode tags on tablets
  src/app/common/components/TagList/TagList.component.tsx
  src/app/common/components/TagList/TagList.styles.scss
Labels: bug

#605 Timeline date fix
  src/app/stores/timeline-store.ts
  src/features/AdminPage/NewStreetcode/TimelineBlock/NewTimelineModal/NewTimelineModal.component.tsx
  src/features/AdminPage/NewStreetcode/TimelineBlock/TimelineBlockAdmin.component.tsx
  src/features/StreetcodePage/TimelineBlock/TimelineItem/TimelineItem.component.tsx
  src/features/StreetcodePage/TimelineBlock/TimelineSlider.component.tsx
  src/features/StreetcodePage/TimelineBlock/TimelineSwiper/TimelineSwiperEdgeBtn/TimelineSwiperEdgeBtn.component.tsx
  src/models/timeline/chronology.model.ts
Labels: bug, duplicate

#607 add constants for screen width
  src/app/common/constants/screen-sizes.constants.tsx
  src/assets/sass/variables/_variables.sizes.scss
Labels: enhancement

#608 added clear func for close button
  src/app/common/components/modals/Partners/PartnersModal.component.tsx
  src/app/common/components/modals/Partners/PartnersModal.styles.scss
Labels: bug

#610 configure backend link as env variable at runtime
  .env
  Dockerfile
  docker-compose.yml
  env.sh
  public/index.html
  src/app/api/agent.api.ts
Labels: enhancement

#611 News date fix
  src/app/stores/news-store.ts
  src/features/AdminPage/NewsPage/News.component.tsx
  src/features/AdminPage/NewsPage/NewsModal/NewsModal.component.tsx
Labels: bug, duplicate

#613 587 contact us contact email icon is not clickable
  src/features/AdditionalPages/ContactUsPage/MainBlock/ContactBlock/ContactBlock.component.tsx
  src/features/AdditionalPages/ContactUsPage/MainBlock/ContactBlock/ContactBlock.styles.scss
  src/features/AdditionalPages/PrivatePolicyPage/SubSections/SubSectionFifth/SectionFifth.component.tsx
  src/features/AdditionalPages/PrivatePolicyPage/SubSections/SubSectionSeventh/SectionSeventh.component.tsx
Labels: bug

#616 Message for the user when maintext is being loaded
  src/features/AdminPage/NewStreetcode/TextBlock/TextForm/TextPreview/TextPreview.component.tsx
  src/features/AdminPage/NewStreetcode/TextBlock/TextForm/TextPreview/TextPreview.styles.scss
Labels: bug

#629 Change docker images to centralized repo
  docker-compose.yml
Labels: enhancement

#621 Redesign "Categories for fans" block
  src/app/stores/sources-store.ts
  src/features/AdminPage/ForFansPage/ForFansMainPage.component.tsx
  src/features/AdminPage/ForFansPage/ForFansPage/CategoryAdminModal.component.tsx
  src/features/AdminPage/ForFansPage/ForFansPage/ForFansPage.component.tsx
  src/features/AdminPage/ForFansPage/ForFansPage/ForFansPage.style.scss
  src/features/AdminPage/ForFansPage/ForFansPage/SourceItem.tsx
Labels: duplicate, enhancement

#623 Partners link validation hot fix
  src/features/AdminPage/PartnersPage/PartnerModal/PartnerModal.component.tsx
Labels: bug

#624 Fix "До стріткодів" and "задонатити" buttons clickable area
  src/features/MainPage/StaticBanners/StaticBanner.component.tsx
Labels: bug, duplicate

#625 Added floating of the button
  src/features/AdditionalPages/PartnersPage/ModalButtons/PartnersBtnCircle/PartnersBtnCircle.component.tsx
  src/features/AdditionalPages/PartnersPage/ModalButtons/PartnersBtnCircle/PartnersBtnCircle.styles.scss
  src/features/AdditionalPages/PartnersPage/Partners.component.tsx
  src/features/AdditionalPages/PartnersPage/Partners.styles.scss
Labels: bug

#631 Streetcode link higlighting
  src/features/StreetcodePage/MainBlock/BreadCrumb/BreadCrumb.styles.scss
Labels: bug

#632 Fix progress bar items clickable area
  src/features/ProgressBar/ProgressBarSection/ProgressBarSection.component.tsx
Labels: bug, duplicate

#634 fixed redirect issue
  src/features/StreetcodeCatalogPage/StreetcodeCatalogItem/StreetcodeCatalogItem.component.tsx
Labels: bug

#627 added validation for date field admin panel
  src/features/AdminPage/NewStreetcode/MainBlock/DatePickerPart.component.tsx
Labels: bug, enhancement

#636 Categories hot fix
  src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx
Labels: bug

#643 533 the трохи ще button
  package.json
  src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/TextEditor.component.tsx
  src/features/StreetcodePage/TextBlock/ReadMore/ReadMore.component.tsx
  src/index.d.ts
Labels: bug

#626 Fix audio buttons
  src/app/common/components/modals/ListenText/ListenText.styles.scss
  src/features/AdminPage/NewStreetcode/MainBlock/FileInputsPart.component.tsx
  src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.style.scss
Labels: bug

#640 fixed displaying text on the first click
  src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx
Labels: bug

#638 modified redirect
  src/features/StreetcodeCatalogPage/StreetcodeCatalogItem/StreetcodeCatalogItem.component.tsx
Labels: bug

#653 fix required audio
  src/features/AdminPage/NewStreetcode/MainBlock/FileInputsPart.component.tsx
  src/features/StreetcodePage/QRBlock/QRMobile/QRMobile.component.tsx
Labels: bug

#656 Fixing bugs 604-605
  src/features/StreetcodePage/HeadingBlock/BlockHeading.component.tsx
  src/features/StreetcodePage/HeadingBlock/BlockHeading.styles.scss
  src/features/StreetcodePage/TextBlock/TextBlock.component.tsx
Labels: bug

#639 Fixed button size
  src/features/AdditionalPages/ContactUsPage/ContactUs.styles.scss
Labels: bug, styles

#618 Fixed button color on hover
  src/features/AdditionalPages/NewsPage/News.styles.scss
Labels: bug, styles

#628 Vlad news button
  src/features/MainPage/NewsSlider/NewsSlider.component.tsx
  src/features/MainPage/NewsSlider/NewsSlider.styles.scss
Labels: bug

#660 Hyphen + hide block if no ar url
  src/features/StreetcodePage/QRBlock/QR.component.tsx
  src/features/StreetcodePage/QRBlock/QRMobile/QRMobile.component.tsx
Labels: bug

#644 Fixed news displaying
  src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.component.tsx
  src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.styles.scss
Labels: bug, styles

#666 fixed team modal
  src/features/AdminPage/TeamPage/TeamModal/TeamModal.component.tsx
Labels: bug

#664 fix styles
  src/features/MainPage/StaticBanners/StaticBanner.styles.scss
Labels: styles

#670 added ticker string to about us
  src/app/api/team/tickerString.api.tsx
  src/app/common/constants/api-routes.constants.ts
  src/features/AboutUsPage/AboutUsPage.component.tsx
  src/features/StreetcodePage/Streetcode.component.tsx
  src/features/StreetcodePage/TickerBlock/Ticker.component.tsx
Labels: enhancement

#669 position fix
  src/features/AdminPage/TeamPage/TeamPage.component.tsx
Labels: bug

#649 Made modal window clickable
  src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.component.tsx
Labels: bug

#668 Fixed input shift
  src/features/AdditionalPages/SupportUsPage/components/DonationBlock.component.tsx
Labels: bug

#673 Change CSS StreetcodeCatalog
  src/features/StreetcodeCatalogPage/StreetcodeCatalog.styles.scss
  src/features/StreetcodeCatalogPage/StreetcodeCatalogItem/StreetcodeCatalogItem.styles.scss
Labels: bug

#675 Changed the speed
  src/features/MainPage/TopCarousel/TopCarousel.component.tsx
  src/features/MainPage/TopCarousel/TopCarousel.styles.scss
Labels: bug, styles

#676 Streetcode page loading fix
  src/app/stores/streetcode-page-loader-store.ts
  src/features/AdminPage/NewStreetcode/MainBlock/FileInputsPart.component.tsx
  src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx
Labels: bug, enhancement

#677 - add empty try-catch to make error handled on Main Page
  src/features/MainPage/InstagramBlock/InstagramBlock.component.tsx
Labels: bug

#681 Added underline for link
  src/features/StreetcodePage/TextBlock/AdditionalTextBlock/AdditionalTextBlock.styles.scss
Labels: bug, styles

#686 Fix for dots carousel
  src/features/MainPage/TopCarousel/TopCarousel.styles.scss
Labels: bug

#665 662 clickable cards in blocks
  src/features/AdminPage/ForFansPage/ForFansPage/CategoryAdminModal.component.tsx
  src/features/AdminPage/NewStreetcode/MainBlock/PreviewFileModal/PreviewFileModal.component.tsx
  src/features/AdminPage/NewStreetcode/TimelineBlock/NewTimelineModal/NewTimelineModal.component.tsx
  src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.component.tsx
  src/features/MainPage/StreetcodeSlider/StreetcodeSliderItem/StreetcodeSliderItem.component.tsx
Labels: bug

#680 Fix shadows
  src/app/common/components/ScrollToTopBtn/ScrollToTopBtn.styles.scss
  src/app/common/components/modals/Donates/DonatesModal.styles.scss
  src/app/common/components/modals/HeaderLogin/HeaderLoginModal.styles.scss
  src/app/common/components/modals/ListenText/ListenText.styles.scss
  src/app/common/components/modals/Partners/PartnersModal.styles.scss
  src/app/common/components/modals/RelatedFigures/RelatedFigureItemModal.styles.scss
  src/app/common/components/modals/Survey/SurveyModal.styles.scss
  src/assets/sass/variables/_variables.colors.scss
  src/features/AdditionalPages/ContactUsPage/ContactUs.styles.scss
  src/features/AdditionalPages/ContactUsPage/MainBlock/ContactBlock/ContactBlock.styles.scss
  src/features/AdditionalPages/NewsPage/News.styles.scss
  src/features/AdditionalPages/PartnersPage/ModalButtons/PartnersBtnCircle/PartnersBtnCircle.styles.scss
  src/features/AdditionalPages/SupportUsPage/components/DonationBlock.styles.scss
  src/features/AdminPage/NewStreetcode/MapBlock/StatisticsStreetcodeAdmin/StatisticsAdmin.styles.scss
  src/features/MainPage/StaticBanners/StaticBanner.styles.scss
  src/features/StreetcodePage/DonateBtn/DonateBtn.styles.scss
  src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.styles.scss
Labels: bug

#682 Fix "Трохи ще" button
  package-lock.json
  package.json
  src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/TextEditor.component.tsx
  src/features/StreetcodePage/TextBlock/ReadMore/ReadMore.component.tsx
  src/index.d.ts
Labels: bug

#690 - fix all sliders (slick && swiper) not showing all dots on overflow
  src/app/layout/app/App.component.tsx
  src/app/layout/app/slick-slider.overrides.scss
  src/features/MainPage/TeamSlider/TeamComponent.styles.scss
  src/features/StreetcodePage/ArtGalleryBlock/ArtGalleryBlock.styles.scss
  src/features/StreetcodePage/TimelineBlock/TimelineSwiper/TimelineSwiper.styles.scss
Labels: bug

#694 Fixed - in donates
  src/app/common/components/modals/Donates/DonatesModal.component.tsx
Labels: bug

#696 Remove loading video waiting
  src/features/StreetcodePage/TextBlock/TextBlock.component.tsx
Labels: bug

#684 683 main page redundant functionality in news block
  src/features/MainPage/Heading/Heading.component.tsx
  src/features/MainPage/NewsSlider/NewsSlider.component.tsx
Labels: bug

#701 News display fix
  src/features/MainPage/Heading/Heading.styles.scss
  src/features/MainPage/NewsSlider/NewsSlider.styles.scss
  src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.component.tsx
  src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.styles.scss
Labels: bug

#706 fixed scroll after first render
  src/features/StreetcodePage/TextBlock/ReadMore/ReadMore.component.tsx
Labels: bug

#693 Add pagination to street code arts/frontend
  src/app/api/media/streetcode-art.api.ts
  src/app/common/constants/api-routes.constants.ts
  src/app/stores/streetcode-art-store.ts
  src/features/StreetcodePage/ArtGalleryBlock/ArtGalleryBlock.component.tsx
Labels: bug

#695 Dots banner sliders
  src/features/MainPage/TopCarousel/TopCarousel.styles.scss
Labels: bug, styles

#698 Fix dots mainpage sliders
  src/app/layout/app/slick-slider.overrides.scss
  src/features/SlickSlider/SlickSlider.styles.scss
  src/features/StreetcodePage/TimelineBlock/TimelineSwiper/TimelineSwiper.styles.scss
Labels: bug, styles

#699 fix height after which button is visible
  src/app/common/components/ScrollToTopBtn/ScrollToTopBtn.component.tsx
Labels: bug, enhancement

#700 Fixed wowfact modal window opening
  src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.component.tsx
  src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.styles.scss
Labels: bug

#705 Vlad image cropping fix
  src/features/MainPage/StreetcodeSlider/StreetcodeSliderItem/StreetcodeSliderItem.styles.scss
  src/features/SlickSlider/SlickSlider.styles.scss
  src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx
  src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.component.tsx
  src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.styles.scss
Labels: bug, styles

#710 Fix more button
  src/app/common/components/modals/Donates/DonatesModal.styles.scss
  src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/TextEditor.component.tsx
  src/features/StreetcodePage/HeadingBlock/BlockHeading.component.tsx
  src/features/StreetcodePage/HeadingBlock/BlockHeading.styles.scss
  src/features/StreetcodePage/TextBlock/ReadMore/ReadMore.component.tsx
  src/features/StreetcodePage/TextBlock/ReadMore/ReadMore.styles.scss
  src/features/StreetcodePage/TextBlock/TextBlock.styles.scss
Labels: bug

#725 sliders
  src/app/api/team/positions.api.ts
  src/app/common/constants/api-routes.constants.ts
  src/features/AboutUsPage/TeamMembers/TeamMembers.component.tsx
  src/features/AboutUsPage/TeamMembers/TeamPositionsSlider/TeamPostionSlider.component.tsx
Labels: enhancement

#727 slider
  src/app/api/team/positions.api.ts
  src/app/api/team/team.api.ts
  src/app/common/constants/api-routes.constants.ts
  src/features/AboutUsPage/TeamMembers/TeamMembers.component.tsx
  src/features/AboutUsPage/TeamMembers/TeamPositionsSlider/TeamPostionSlider.component.tsx
Labels: enhancement
