Repository ita-social-projects/StreetCode_Client, pull requests merged in 2023-07, with the labels that each got.

#422 FIX - Not Found Page & Donates Page
  src/features/AdditionalPages/NotFoundPage/NotFound.component.tsx
  src/features/AdditionalPages/NotFoundPage/NotFound.styles.scss
  src/features/AdditionalPages/SupportUsPage/SupportUs.styles.scss
Labels: bug

#439 Replace -- to - =)
  src/app/common/components/modals/InterestingFacts/FactsAdminModal/InterestingFactsAdminModal.component.tsx
  src/features/AdminPage/NewStreetcode/InterestingFactsBlock/FactsAdminModal/InterestingFactsAdminModal.component.tsx
  src/features/AdminPage/NewStreetcode/InterestingFactsBlock/InterestingFactsBlock.component.tsx
  src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.component.tsx
  src/features/StreetcodePage/QRBlock/QR.component.tsx
Labels: enhancement

#408 Fixed 'Copy check' button and added a copy message
  src/features/AdditionalPages/SupportUsPage/SupportUs.component.tsx
  src/features/AdditionalPages/SupportUsPage/SupportUs.styles.scss
Labels: bug

#386 [Fixed bug] 404 redirect
  src/features/StreetcodePage/Streetcode.component.tsx
Labels: bug

#383 Adaptive for banner and partners
  src/assets/images/main-page/ornament_mobile.svg
  src/features/MainPage/PartnersBlockMain/PartnersBlockMain.styles.scss
  src/features/MainPage/StaticBanners/StaticBanner.component.tsx
  src/features/MainPage/StaticBanners/StaticBanner.styles.scss
Labels: styles

#435 fixed sections name
  src/features/ProgressBar/NavigableBlockWrapper.component.tsx
Labels: bug

#440 Fix streetcode publish button
  src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
  src/models/streetcode/streetcode-types.model.ts
Labels: bug

#427 Modals validation and UI improvements
  src/features/AdminPage/PartnersPage/PartnerModal/PartnerModal.component.tsx
  src/features/AdminPage/PartnersPage/PartnerModal/PartnerModal.styles.scss
  src/features/StreetcodePage/PartnersBlock/PartnerItem/PartnerContent/PartnerContent.component.tsx
  src/models/partners/partners.model.ts
Labels: bug

#426 Fix errors admin panel
  src/app/layout/header/HeaderSkeleton/HeaderSkeleton.component.tsx
  src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx
  src/features/AdminPage/NewStreetcode/InterestingFactsBlock/FactsAdminModal/InterestingFactsAdminModal.component.tsx
  src/features/AdminPage/NewStreetcode/MainBlock/FileInputsPart.component.tsx
  src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.component.tsx
  src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
Labels: bug

#442 Display the video if there is a link
  src/features/StreetcodePage/TextBlock/TextBlock.component.tsx
Labels: bug

#450 Fix art preview content height
  src/features/AdminPage/NewStreetcode/ArtGallery/components/ArtGallery/ArtGalleryAdminStyles.styles.scss
Labels: bug, duplicate

#437 border-fix
  src/app/common/components/modals/Partners/PartnersModal.styles.scss
  src/features/AdditionalPages/ContactUsPage/MainBlock/ContactForm/ContactForm.styles.scss
Labels: styles

#444 Fix update again
  src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
  src/models/streetcode/text-contents.model.ts
Labels: bug

#434 AR button fix
  src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx
Labels: bug

#454 Added translation for Tiny modals
  src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx
  src/features/AdminPage/NewStreetcode/TextBlock/TextForm/AdditionTextBlock/AdditionalTextBlockAdminForm.component.tsx
Labels: enhancement

#458 Added "Додати нову категорію..." button on forFans modal
  src/features/AdminPage/ForFansPage/ForFansPage/CategoryAdminModal.component.tsx
  src/features/AdminPage/ForFansPage/ForFansPage/ForFansPage.component.tsx
  src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx
  src/features/AdminPage/PageBar/PageBar.component.tsx
Labels: enhancement

#455 fix publish and draft date
  src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
  src/models/streetcode/streetcode-types.model.ts
Labels: bug

#464 Fix update
  src/features/AdminPage/NewStreetcode/HistoryRelations/HistoryRelations.component.tsx
  src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
Labels: bug

#461 implemented confirmation window when changing streetcode status
  src/features/AdminPage/StreetcodesTable/StreetcodesTable.component.tsx
Labels: duplicate, enhancement

#462 added instagram button, fixed dots
  src/features/MainPage/InstagramBlock/InstagramBlock.component.tsx
  src/features/MainPage/InstagramBlock/InstagramBlock.styles.scss
Labels: bug, styles

#465 431 confirmation alerts streetcodeedit page
  src/features/AdminPage/NewStreetcode/ARBlock/ARBlock.component.tsx
  src/features/AdminPage/NewStreetcode/ArtGallery/ArtGallery.component.tsx
  src/features/AdminPage/NewStreetcode/ArtGallery/components/Download.component.tsx
  src/features/AdminPage/NewStreetcode/ArtGallery/components/PreviewImageModal/PreviewImageModal.component.tsx
  src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx
  src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansBlock.component.tsx
  src/features/AdminPage/NewStreetcode/HistoryRelations/HistoryRelations.component.tsx
  src/features/AdminPage/NewStreetcode/HistoryRelations/components/InputPanel.component.tsx
  src/features/AdminPage/NewStreetcode/InterestingFactsBlock/FactsAdminModal/InterestingFactsAdminModal.component.tsx
  src/features/AdminPage/NewStreetcode/InterestingFactsBlock/InterestingFactsAdminItem/InterestingFactsAdminItem.component.tsx
  src/features/AdminPage/NewStreetcode/InterestingFactsBlock/InterestingFactsBlock.component.tsx
  src/features/AdminPage/NewStreetcode/MainBlock/DatePickerPart.component.tsx
  src/features/AdminPage/NewStreetcode/MainBlock/FileInputsPart.component.tsx
  src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.component.tsx
  src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
  src/features/AdminPage/NewStreetcode/PartnerBlock/PartnerBlockAdmin.components.tsx
  src/features/AdminPage/NewStreetcode/SubtitileBlock/SubtitleBlock.component.tsx
  src/features/AdminPage/NewStreetcode/TextBlock/TextBlock.component.tsx
  src/features/AdminPage/NewStreetcode/TextBlock/TextForm/AdditionTextBlock/AdditionalTextBlockAdminForm.component.tsx
  src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/LinkEditor.component.tsx
  src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/TextEditor.component.tsx
  src/features/AdminPage/NewStreetcode/TextBlock/TextForm/TextForm.component.tsx
  src/features/AdminPage/NewStreetcode/TimelineBlock/NewTimelineItem/NewTimelineItem.component.tsx
  src/features/AdminPage/NewStreetcode/TimelineBlock/NewTimelineModal/NewTimelineModal.component.tsx
  src/features/AdminPage/NewStreetcode/TimelineBlock/TimelineBlockAdmin.component.tsx
  src/features/AdminPage/PartnersPage/PartnerModal/PartnerModal.component.tsx
Labels: enhancement

#481 Art Gallery multi delete. Recreating pull request after mistaken merge.
  src/features/AdminPage/NewStreetcode/ArtGallery/components/Download.component.tsx
  src/features/AdminPage/NewStreetcode/ArtGallery/components/DownloadStyles.styles.scss
Labels: enhancement

#491 fixed display of the tag modal window on mobile devices
  src/app/common/components/TagList/TagList.styles.scss
Labels: bug

#498 [Admin/Chronology] Changed max length of title to 26
  src/features/AdminPage/NewStreetcode/TimelineBlock/NewTimelineModal/NewTimelineModal.component.tsx
Labels: bug

#493 Donate checkbox align and blue borders fix
  src/features/AdditionalPages/SupportUsPage/components/DonationBlock.styles.scss
Labels: bug, duplicate

#495 fix name display of category after adding on admin page
  src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx
  src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansBlock.component.tsx
Labels: bug

#496 Added translation for art gallery modal
  src/features/AdminPage/NewStreetcode/ArtGallery/components/PreviewImageModal/PreviewImageModal.component.tsx
Labels: bug

#497 changed word wrap for chronology item block
  src/features/StreetcodePage/TimelineBlock/TimelineItem/TimelineItem.styles.scss
Labels: bug

#494 Fix related figures admin
  src/app/api/streetcode/streetcodes.api.ts
  src/app/common/constants/api-routes.constants.ts
  src/app/layout/header/HeaderBlock.styles.scss
  src/features/AdminPage/NewStreetcode/HistoryRelations/HistoryRelations.component.tsx
  src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
Labels: bug

#500 fix toolbar
  src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx
Labels: bug, duplicate

#499 Wow fact for fans adaptive fix
  src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.styles.scss
  src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.component.tsx
  src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.styles.scss
  src/features/StreetcodePage/SourcesBlock/Sources.styles.scss
Labels: bug, styles

#503 News modal fix
  src/assets/sass/variables/_variables.colors.scss
  src/features/AdminPage/AdminPage.component.tsx
  src/features/AdminPage/NewsPage/News.component.tsx
  src/features/AdminPage/NewsPage/NewsModal/NewsModal.component.tsx
  src/features/AdminPage/NewsPage/NewsModal/NewsModal.styles.scss
  src/features/AdminPage/PartnersPage/PartnerModal/PartnerModal.component.tsx
  src/features/AdminPage/PartnersPage/PartnerModal/PartnerModal.styles.scss
  src/models/news/news.model.ts
Labels: bug

#504 489 fix reloadredirect confirmation
  src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
Labels: bug

#511 Duplicate url fix, Check Index fix
  src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.component.tsx
  src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
Labels: bug

#510 401 adminchronology block when the admin add more than 50 characters to the context field all text is erased
  src/features/AdminPage/NewStreetcode/TimelineBlock/NewTimelineModal/NewTimelineModal.component.tsx
Labels: bug

#514 fix catalogue loading
  src/app/common/hooks/scrolling/useOnScreen.hook.ts
Labels: bug, duplicate

#518 Data format fix
  src/features/AdminPage/StreetcodesTable/StreetcodesTable.component.tsx
Labels: bug

#520 Added character counter
  src/features/AdminPage/NewStreetcode/InterestingFactsBlock/FactsAdminModal/InterestingFactsAdminModal.component.tsx
Labels: bug

#523 Added tags list sorting in alphavbetical order
  src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.component.tsx
Labels: bug, enhancement

#524 fixed char limit on admin page in text block
  src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/TextEditor.component.tsx
Labels: bug

#521 No scrolling when clicking on "Назва" (chronology)
  src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.component.tsx
  src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
  src/features/AdminPage/NewStreetcode/StreetCodeBlock/StreetCodeBlock.component.tsx
Labels: bug

#516 Fixing displaying text on text editor on admin page
  src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/TextEditor.component.tsx
Labels: bug

#525 423 adminchronology block context symbolscounter
  src/features/AdminPage/NewStreetcode/TimelineBlock/NewTimelineModal/NewTimelineModal.component.tsx
  src/features/AdminPage/NewStreetcode/TimelineBlock/NewTimelineModal/NewTimelineModal.style.scss
Labels: enhancement

#531 Fixed logo on main page
  src/assets/images/header/Streetcode_logo.svg
  src/assets/images/header/Streetcode_logo_mobile.svg
Labels: bug

#522 Fix streetcode link background
  src/features/StreetcodePage/MainBlock/BreadCrumb/BreadCrumb.styles.scss
Labels: bug, duplicate

#529 Update DonationBlock.component.tsx
  src/features/AdditionalPages/SupportUsPage/components/DonationBlock.component.tsx
Labels: bug

#539 Added photo preview
  src/features/AdminPage/ForFansPage/ForFansPage/CategoryAdminModal.component.tsx
Labels: bug

#534 Made a localization for "Для фанатів" modal window
  src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx
Labels: styles

#540 fixed display of name and surname
  src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
Labels: bug

#506 488 admin page video input validation
  package.json
  src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/LinkEditor.component.tsx
  src/features/StreetcodePage/TextBlock/TextBlock.component.tsx
Labels: bug, enhancement

#517 Modals for delete
  src/features/AdminPage/NewStreetcode/MainBlock/FileInputsPart.component.tsx
Labels: enhancement

#538 Vlad character limit for authorship and for fans
  src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx
  src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansBlock.component.tsx
  src/features/AdminPage/NewStreetcode/TextBlock/TextForm/AdditionTextBlock/AdditionalTextBlockAdminForm.component.tsx
  src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/TextEditor.component.tsx
  src/features/AdminPage/NewStreetcode/TextBlock/TextForm/TextForm.component.tsx
Labels: bug

#542 fixed displaying load gif on wide monitors
  src/features/StreetcodePage/Streetcode.styles.scss
Labels: bug, styles

#543 Bug/fixed deleting second date on admin page
  src/features/AdminPage/NewStreetcode/MainBlock/DatePickerPart.component.tsx
Labels: bug

#548 make a validation to an Animation block
  src/features/AdminPage/NewStreetcode/MainBlock/FileInputsPart.component.tsx
Labels: bug

#552 Fix to unlock date filed after selected firsting date
  src/features/AdminPage/NewStreetcode/MainBlock/DatePickerPart.component.tsx
Labels: bug

#554 Fix/text upload in main text on admin page
  src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/TextEditor.component.tsx
Labels: bug

#555 Fixed image description saving
  src/features/AdminPage/NewStreetcode/InterestingFactsBlock/FactsAdminModal/InterestingFactsAdminModal.component.tsx
Labels: bug

#556 Fix arts limit
  src/features/AdminPage/NewStreetcode/ArtGallery/components/Download.component.tsx
Labels: bug, duplicate

#557 547 adminpreviews preview in poor quality
  src/features/AdminPage/ForFansPage/ForFansPage/CategoryAdminModal.component.tsx
  src/features/AdminPage/ForFansPage/ForFansPage/ForFansPage.component.tsx
  src/features/AdminPage/ForFansPage/ForFansPage/SourceItem.tsx
  src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx
  src/features/AdminPage/NewStreetcode/MainBlock/PreviewFileModal/PreviewFileModal.component.tsx
Labels: bug, enhancement

#558 fixed updating streetcode streetcode with video
  src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/LinkEditor.component.tsx
Labels: bug

#560 Empty alias isn't displayed
  src/features/StreetcodeCatalogPage/StreetcodeCatalogItem/StreetcodeCatalogItem.component.tsx
Labels: bug

#562 fix text load
  src/features/StreetcodePage/TextBlock/SearchTerms/SearchTerms.component.tsx
  src/features/StreetcodePage/TextBlock/TextBlock.component.tsx
Labels: bug

#563 532 tags validation UI
  src/app/common/utils/selectValidation.utility.tsx
  src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.component.tsx
  src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.style.scss
  src/features/AdminPage/NewStreetcode/TimelineBlock/NewTimelineModal/NewTimelineModal.component.tsx
Labels: bug, enhancement

#566 add survey button and change links open logic
  src/app/common/components/modals/HeaderLogin/HeaderLoginModal.component.tsx
  src/app/common/components/modals/Survey/SurveyModal.component.tsx
Labels: enhancement

#564 Fixed text updating
  src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
Labels: bug
