Repository ita-social-projects/StreetCode_Client, pull requests merged in 2023-05, with the labels that each got.

#214 Added routes to the menu and fixed bgcolor
  src/app/layout/header/HeaderDrawer/HeaderDrawer.component.tsx
  src/app/layout/header/HeaderDrawer/MainDrawerHeaderItems/MainDrawerList.component.tsx
  src/features/AdditionalPages/ContactUsPage/ContactUs.styles.scss
Labels: enhancement, styles

#227 Fix admin-panel styles
  src/features/AdminPage/NewStreetcode/ArtGallery/ArtGallery.component.tsx
  src/features/AdminPage/NewStreetcode/ArtGallery/ArtGallery.styles.scss
  src/features/AdminPage/NewStreetcode/HistoryRelations/HistoryRelations.component.tsx
  src/features/AdminPage/NewStreetcode/HistoryRelations/HistoryRelations.styles.scss
  src/features/AdminPage/NewStreetcode/InterestingFactsBlock/InterestingFactsBlock.component.tsx
  src/features/AdminPage/NewStreetcode/InterestingFactsBlock/InterestingFactsBlock.style.scss
  src/features/AdminPage/NewStreetcode/MainBlock/DatePickerPart.component.tsx
  src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.component.tsx
  src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.style.scss
  src/features/AdminPage/NewStreetcode/MainNewStreetcode.styles.scss
  src/features/AdminPage/NewStreetcode/MapBlock/MapBlockAdmin.styles.scss
  src/features/AdminPage/NewStreetcode/MapBlock/StatisticsToponymsAdmin/SearchMenu.styles.scss
  src/features/AdminPage/NewStreetcode/MapBlock/StatisticsToponymsAdmin/StatisticsToponymsAdmin.styles.scss
  src/features/AdminPage/NewStreetcode/PartnerBlock/PartnerBlockAdmin.components.tsx
  src/features/AdminPage/NewStreetcode/PartnerBlock/PartnerBlockAdmin.style.scss
  src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/TextEditor.component.tsx
Labels: styles

#238 add redirect to partners page
  src/app/common/components/modals/HeaderLogin/HeaderLoginModal.component.tsx
Labels: bug

#236 Stop ticker on hover
  src/features/StreetcodePage/TickerBlock/Ticker.component.tsx
  src/features/StreetcodePage/TickerBlock/Ticker.styles.scss
Labels: bug

#232 add modal styles
  src/app/common/components/modals/Terms/AddTerm/AddTermModal.component.tsx
  src/features/AdminPage/AdminModal.styles.scss
  src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx
  src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.styles.scss
  src/features/AdminPage/NewStreetcode/InterestingFactsBlock/FactsAdminModal/InterestingFactsAdminModal.component.tsx
  src/features/AdminPage/NewStreetcode/InterestingFactsBlock/FactsAdminModal/InterestingFactsAdminModal.style.scss
  src/features/AdminPage/NewStreetcode/TimelineBlock/NewTimelineModal/NewTimelineModal.component.tsx
  src/features/AdminPage/NewStreetcode/TimelineBlock/NewTimelineModal/NewTimelineModal.style.scss
  src/features/AdminPage/PartnersPage/PartnerModal/PartnerModal.component.tsx
  src/features/AdminPage/PartnersPage/PartnerModal/PartnerModal.styles.scss
Labels: styles

#239 fixed buttons
  src/features/AdminPage/StreetcodesTable/SearchMenu.component.tsx
  src/features/AdminPage/StreetcodesTable/StreetcodesTable.component.tsx
Labels: enhancement

#240 Checkbox styles admin add
  src/features/AdminPage/AdminModal.styles.scss
  src/features/AdminPage/NewStreetcode/MainNewStreetcode.styles.scss
  src/features/AdminPage/NewStreetcode/MapBlock/MapAdmin/MapAdmin.styles.scss
  src/features/AdminPage/NewStreetcode/MapBlock/StatisticsToponymsAdmin/StatisticsToponymsAdmin.component.tsx
  src/features/AdminPage/PartnersPage/PartnerModal/PartnerModal.styles.scss
Labels: styles

#242 redirect to main page
  src/features/AdditionalPages/NotFoundPage/NotFound.component.tsx
Labels: bug

#243 fix-button-width-margin
  src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.styles.scss
Labels: styles

#244 add-display-none
  src/features/StreetcodePage/ArtGalleryBlock/ArtGalleryBlock.component.tsx
  src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.component.tsx
  src/features/StreetcodePage/PartnersBlock/Partners.component.tsx
  src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigures.component.tsx
  src/features/StreetcodePage/SourcesBlock/Sources.component.tsx
  src/features/StreetcodePage/Streetcode.styles.scss
  src/features/StreetcodePage/TextBlock/TextBlock.component.tsx
  src/features/StreetcodePage/TickerBlock/Ticker.component.tsx
  src/features/StreetcodePage/TimelineBlock/TimelineBlock.component.tsx
Labels: enhancement

#246 added reloading in Related History block
  src/app/common/components/modals/RelatedFigures/RelatedFigureItemModal.component.tsx
  src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.component.tsx
Labels: bug

#247 admin inputnumberFix
  src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.component.tsx
Labels: bug

#245 change - to —
  src/app/common/components/modals/InterestingFacts/FactsAdminModal/InterestingFactsAdminModal.component.tsx
  src/app/common/components/modals/Partners/PartnersModal.component.tsx
  src/features/AdditionalPages/ContactUsPage/MainBlock/ContactForm/ContactForm.component.tsx
  src/features/AdditionalPages/PrivatePolicyPage/SubSections/SubSectionFifth/SectionFifth.component.tsx
  src/features/AdditionalPages/PrivatePolicyPage/SubSections/SubSectionFirst/SectionFirst.component.tsx
  src/features/AdditionalPages/PrivatePolicyPage/SubSections/SubSectionFourth/SectionFourth.component.tsx
  src/features/AdditionalPages/PrivatePolicyPage/SubSections/SubSectionSecond/SectionSecond.component.tsx.tsx
  src/features/AdditionalPages/PrivatePolicyPage/SubSections/SubSectionSeventh/SectionSeventh.component.tsx
  src/features/AdditionalPages/PrivatePolicyPage/SubSections/SubSectionSixth/SectionSixth.component.tsx
  src/features/AdditionalPages/PrivatePolicyPage/SubSections/SubSectionThird/SectionThird.component.tsx
  src/features/AdditionalPages/SupportUsPage/SupportUs.component.tsx
  src/features/AdminPage/NewStreetcode/ArtGallery/ArtGallery.component.tsx
  src/features/AdminPage/NewStreetcode/InterestingFactsBlock/FactsAdminModal/InterestingFactsAdminModal.component.tsx
  src/features/AdminPage/NewStreetcode/InterestingFactsBlock/InterestingFactsBlock.component.tsx
  src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.component.tsx
  src/features/StreetcodePage/QRBlock/QR.component.tsx
  src/features/StreetcodePage/QRBlock/QRMobile/QRMobile.component.tsx
Labels: styles

#252 New adaptive tablet arts and algoritm for them
  src/app/common/components/FileUploader/FileUploader.component.tsx
  src/app/common/components/modals/Lightbox/LightboxComponent.styles.scss
  src/features/AdminPage/NewStreetcode/ArtGallery/components/ArtGallery/ArtGalleryAdminBlock.component.tsx
  src/features/AdminPage/NewStreetcode/ArtGallery/components/Download.component.tsx
  src/features/AdminPage/StreetcodesTable/StreetcodesTable.component.tsx
  src/features/StreetcodePage/ArtGalleryBlock/ArtGalleryBlock.component.tsx
  src/features/StreetcodePage/ArtGalleryBlock/ArtGalleryBlock.styles.scss
  src/features/StreetcodePage/ArtGalleryBlock/ArtGalleryItem/ArtGallerySlideItem.component.tsx
  src/features/StreetcodePage/ArtGalleryBlock/ArtGalleryItem/ArtGallerySlideItem.styles.scss
  src/features/StreetcodePage/ArtGalleryBlock/ArtGalleryListOfItem/ArtGallerySlide.styles.scss
  src/features/StreetcodePage/Streetcode.component.tsx
  src/models/media/image.model.ts
Labels: enhancement

#248 [FIX] Drawer bugs, link change and buttons position fix.
  src/app/layout/header/HeaderDrawer/HeaderDrawer.component.tsx
  src/app/layout/header/HeaderDrawer/HeaderDrawer.styles.scss
  src/app/layout/header/HeaderDrawer/HeaderDrawerItem/HeaderDrawerItem.component.tsx
  src/app/layout/header/HeaderDrawer/HeaderDrawerItem/HeaderDrawerItem.styles.scss
  src/app/layout/header/HeaderDrawer/MainDrawerHeaderItems/MainDrawerList.component.tsx
  src/app/router/Routes.tsx
  src/assets/images/utils/Cancel_btn_drawer_mobile.svg
  src/features/StreetcodePage/Streetcode.styles.scss
Labels: bug, enhancement

#254 minor changes
  src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.component.tsx
Labels: styles

#258 Created store, Front admin for fans and made slider on streetcode pag…
  src/app/api/sources/sources.api.ts
  src/app/common/components/modals/Sources/SourcesModal.component.tsx
  src/app/common/components/modals/Sources/SourcesModal.styles.scss
  src/app/stores/root-store.ts
  src/app/stores/sourceadmin-store.ts
  src/app/stores/sources-store.ts
  src/assets/images/utils/ModalMobile.png
  src/assets/images/utils/ModalTablet.png
  src/features/AdminPage/ForFansPage/ForFansMainPage.component.tsx
  src/features/AdminPage/ForFansPage/ForFansMainPage.style.scss
  src/features/AdminPage/ForFansPage/ForFansPage/ForFansPage.component.tsx
  src/features/AdminPage/ForFansPage/ForFansPage/ForFansPage.style.scss
  src/features/AdminPage/ForFansPage/ForFansPage/SourceItem.tsx
  src/features/StreetcodePage/SourcesBlock/SourceItem/SourceItem.styles.scss
  src/features/StreetcodePage/SourcesBlock/Sources.component.tsx
  src/features/StreetcodePage/SourcesBlock/Sources.styles.scss
  src/models/sources/sources.model.ts
Labels: enhancement, styles

#269 Hot fix sources
  src/app/api/sources/sources.api.ts
  src/app/common/constants/api-routes.constants.ts
  src/features/AdminPage/ForFansPage/ForFansMainPage.style.scss
  src/features/StreetcodePage/SourcesBlock/SourceItem/SourceItem.styles.scss
  src/features/StreetcodePage/SourcesBlock/Sources.component.tsx
  src/features/StreetcodePage/SourcesBlock/Sources.styles.scss
Labels: bug

#272 admin for team
  src/app/api/team/positions.api.ts
  src/app/api/team/team.api.ts
  src/app/common/constants/api-routes.constants.ts
  src/app/common/constants/frontend-routes.constants.ts
  src/app/router/Routes.tsx
  src/app/stores/position-store.ts
  src/app/stores/root-store.ts
  src/app/stores/team-store.ts
  src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
  src/features/AdminPage/NewStreetcode/PartnerBlock/PartnerBlockAdmin.components.tsx
  src/features/AdminPage/PageBar/PageBar.component.tsx
  src/features/AdminPage/TeamPage/TeamLink.component.tsx
  src/features/AdminPage/TeamPage/TeamModal/TeamModal.component.tsx
  src/features/AdminPage/TeamPage/TeamModal/TeamModal.styles.scss
  src/features/AdminPage/TeamPage/TeamPage.component.tsx
  src/features/AdminPage/TeamPage/TeamPage.styles.scss
  src/features/StreetcodePage/TextBlock/TextBlock.component.tsx
  src/models/team/team.model.ts
  src/models/team/teamResponse.model.ts
Labels: enhancement

#274 Catalog photo fix
  src/features/StreetcodeCatalogPage/StreetcodeCatalogItem/StreetcodeCatalogItem.component.tsx
  src/models/streetcode/streetcode-types.model.ts
Labels: bug

#276 [HOTFIX] For fans link
  src/features/AdminPage/PageBar/PageBar.component.tsx
Labels: bug

#277 [HotFix] Fixing new streetcode route
  src/app/common/constants/frontend-routes.constants.ts
  src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
  src/features/AdminPage/PageBar/PageBar.component.tsx
Labels: bug

#282 Main page katy
  src/assets/images/main-page/heading-squares.component.svg
  src/assets/images/main-page/ornament.svg
  src/features/MainPage/Heading/Heading.component.tsx
  src/features/MainPage/Heading/Heading.styles.scss
  src/features/MainPage/InstagramBlock/InstagramBlock.component.tsx
  src/features/MainPage/InstagramBlock/InstagramBlock.styles.scss
  src/features/MainPage/InstagramBlock/InstagramSliderItem/InstagramPost.model.ts
  src/features/MainPage/InstagramBlock/InstagramSliderItem/InstagramSliderItem.component.tsx
  src/features/MainPage/InstagramBlock/InstagramSliderItem/InstagramSliderItem.styles.scss
  src/features/MainPage/MainPage.component.tsx
  src/features/MainPage/StaticBanners/StaticBanner.component.tsx
  src/features/MainPage/StaticBanners/StaticBanner.styles.scss
Labels: enhancement

#290 News admin page danya
  src/app/api/news/news.api.ts
  src/app/common/constants/api-routes.constants.ts
  src/app/common/constants/frontend-routes.constants.ts
  src/app/router/Routes.tsx
  src/app/stores/news-store.ts
  src/app/stores/root-store.ts
  src/app/stores/sourceadmin-store.ts
  src/features/AdminPage/ForFansPage/ForFansPage/ForFansPage.component.tsx
  src/features/AdminPage/ForFansPage/ForFansPage/SourceItem.tsx
  src/features/AdminPage/NewsPage/News.component.tsx
  src/features/AdminPage/NewsPage/NewsModal/NewsModal.component.tsx
  src/features/AdminPage/PageBar/PageBar.component.tsx
  src/features/StreetcodePage/SourcesBlock/Sources.component.tsx
  src/features/StreetcodePage/TextBlock/SearchTerms/SearchTerms.component.tsx
  src/models/news/news.model.ts
Labels: enhancement

#299 removed important from slick slider class
  src/features/SlickSlider/SlickSlider.styles.scss
  src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.styles.scss
Labels: enhancement

#301 Dev master main page
  src/app/api/streetcode/streetcodes.api.ts
  src/app/api/team/team.api.ts
  src/app/common/constants/api-routes.constants.ts
  src/app/router/Routes.tsx
  src/app/stores/root-store.ts
  src/app/stores/streetcode-mainpage-store.ts
  src/assets/images/footer/Baner_2.png
  src/assets/images/footer/main-page.png
  src/assets/images/footer/main-page2.png
  src/assets/images/footer/main-page3.png
  src/assets/images/footer/main-page4.png
  src/assets/images/main-page/heading-squares.component.svg
  src/assets/images/main-page/ornament.svg
  src/features/AdditionalPages/NewsPage/ModalButtons/DonateBtn/DonateBtnRectangle.component.tsx
  src/features/AdditionalPages/NewsPage/ModalButtons/DonateBtn/DonateBtnRectangle.styles.scss
  src/features/AdditionalPages/NewsPage/News.component.tsx
  src/features/AdditionalPages/NewsPage/Title/Title.component.tsx
  src/features/AdditionalPages/NewsPage/Title/Title.styles.scss
  src/features/AdditionalPages/PartnersPage/PartnersBlock/PartnersBlock.styles.scss
  src/features/AdminPage/NewStreetcode/ArtGallery/components/Download.component.tsx
  src/features/AdminPage/NewStreetcode/MainBlock/DatePickerPart.component.tsx
  src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.component.tsx
  src/features/AdminPage/NewStreetcode/TimelineBlock/NewTimelineModal/NewTimelineModal.component.tsx
  src/features/AdminPage/PageBar/PageBar.component.tsx
  src/features/AdminPage/TeamPage/TeamModal/TeamModal.component.tsx
  src/features/AdminPage/TeamPage/TeamPage.component.tsx
  src/features/MainPage/Heading/Heading.component.tsx
  src/features/MainPage/Heading/Heading.styles.scss
  src/features/MainPage/InstagramBlock/InstagramBlock.component.tsx
  src/features/MainPage/InstagramBlock/InstagramBlock.styles.scss
  src/features/MainPage/InstagramBlock/InstagramSliderItem/InstagramPost.model.ts
  src/features/MainPage/InstagramBlock/InstagramSliderItem/InstagramSliderItem.component.tsx
  src/features/MainPage/InstagramBlock/InstagramSliderItem/InstagramSliderItem.styles.scss
  src/features/MainPage/MainPage.component.tsx
  src/features/MainPage/MainPage.styles.scss
  src/features/MainPage/NewsSlider/NewsSlider.component.tsx
  src/features/MainPage/NewsSlider/NewsSlider.styles.scss
  src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.component.tsx
  src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.styles.scss
  src/features/MainPage/PartnersBlockMain/PartnersBlockMain.component.tsx
  src/features/MainPage/PartnersBlockMain/PartnersBlockMain.styles.scss
  src/features/MainPage/StaticBanners/StaticBanner.component.tsx
  src/features/MainPage/StaticBanners/StaticBanner.styles.scss
  src/features/MainPage/StreetcodeSlider/StreetcodeSlider.component.tsx
  src/features/MainPage/StreetcodeSlider/StreetcodeSlider.styles.scss
  src/features/MainPage/StreetcodeSlider/StreetcodeSliderItem/StreetcodeSliderItem.component.tsx
  src/features/MainPage/StreetcodeSlider/StreetcodeSliderItem/StreetcodeSliderItem.styles.scss
  src/features/MainPage/TeamSlider/TeamComponent.component.tsx
  src/features/MainPage/TeamSlider/TeamComponent.styles.scss
  src/features/MainPage/TeamSlider/TeamItemSlider/TeamItemSlider.component.tsx
  src/features/MainPage/TeamSlider/TeamItemSlider/TeamItemSlider.styles.scss
  src/features/MainPage/TopCarousel/TopCarousel.component.tsx
  src/features/MainPage/TopCarousel/TopCarousel.styles.scss
  src/features/SlickSlider/SlickSliderTeam.component.tsx
  src/features/StreetcodePage/MapBlock/Map/Marker/Marker.styles.scss
  src/models/streetcode/streetcode-types.model.ts
  src/models/timeline/chronology.model.ts
Labels: enhancement

#306 Required field for category in create streetcode
  src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx
Labels: enhancement

#309 Added field for creation date in modal and display on a table
  src/features/AdminPage/NewsPage/News.component.tsx
  src/features/AdminPage/NewsPage/NewsModal/NewsModal.component.tsx
  src/models/news/news.model.ts
Labels: enhancement

#312 fix fact single
  src/features/StreetcodePage/HeadingBlock/BlockHeading.component.tsx
  src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.styles.scss
  src/features/StreetcodePage/TextBlock/TextBlock.styles.scss
Labels: enhancement

#320 Fix support us page styling
  src/features/AdditionalPages/SupportUsPage/SupportUs.component.tsx
  src/features/AdditionalPages/SupportUsPage/SupportUs.styles.scss
Labels: enhancement

#321 fixes
  src/features/AdditionalPages/SupportUsPage/SupportUs.component.tsx
  src/features/AdminPage/NewStreetcode/MainBlock/DatePickerPart.component.tsx
  src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
  src/features/AdminPage/NewStreetcode/TextBlock/TextForm/AdditionTextBlock/AdditionalTextBlockAdminForm.component.tsx
  src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/LinkEditor.component.tsx
  src/features/AdminPage/NewStreetcode/TimelineBlock/NewTimelineModal/NewTimelineModal.component.tsx
Labels: enhancement

#322 Fixed tag modal.
  src/app/common/components/modals/Tags/TagsModal.component.tsx
  src/app/common/components/modals/Tags/TagsModal.styles.scss
  src/app/common/components/modals/Tags/TagsSliderModal/TagsSliderModal.component.tsx
  src/app/common/components/modals/Tags/TagsSliderModal/TagsSliderModal.styles.scss
  src/app/stores/root-store.ts
  src/app/stores/streetcodes-bytag-store.ts
Labels: bug

#326 Fix donation
  src/app/common/components/modals/Donates/DonatesModal.component.tsx
  src/features/MainPage/InstagramBlock/InstagramBlock.component.tsx
  src/features/MainPage/MainPage.component.tsx
  src/models/feedback/donation.model.ts
Labels: bug

#319 [FIX] Linked main page
  src/app/layout/header/HeaderDrawer/HeaderDrawer.component.tsx
Labels: bug

#323 fixed drawer, background, several buttons
  src/app/common/components/modals/Donates/DonatesModal.component.tsx
  src/app/common/components/modals/Donates/DonatesModal.styles.scss
  src/app/common/components/modals/HeaderLogin/HeaderLoginModal.styles.scss
  src/app/layout/header/HeaderDrawer/HeaderDrawer.component.tsx
  src/app/layout/header/HeaderDrawer/HeaderDrawer.styles.scss
  src/assets/sass/variables/_variables.colors.scss
  src/features/AdditionalPages/ContactUsPage/MainBlock/ContactForm/ContactForm.styles.scss
  src/features/AdditionalPages/NotFoundPage/NotFound.component.tsx
  src/features/AdditionalPages/NotFoundPage/NotFound.styles.scss
  src/features/AdditionalPages/PartnersPage/ModalButtons/DonateBtn/DonateBtnRectangle.styles.scss
  src/features/AdditionalPages/PartnersPage/ModalButtons/PartnersBtn/PartnersBtn.styles.scss
  src/features/AdditionalPages/PartnersPage/Partners.styles.scss
  src/features/AdditionalPages/PrivatePolicyPage/PrivatePolicy.styles.scss
  src/features/AdditionalPages/SupportUsPage/components/DonationBlock.component.tsx
  src/features/AdditionalPages/SupportUsPage/components/DonationBlock.styles.scss
  src/features/AdminPage/ForFansPage/ForFansPage/ForFansPage.component.tsx
  src/features/AdminPage/TermDictionary/TermDictionary.component.tsx
  src/features/StreetcodeCatalogPage/StreetcodeCatalog.component.tsx
  src/features/StreetcodeCatalogPage/StreetcodeCatalog.styles.scss
Labels: bug

#330 Fixed data.stopPropagation() is not a function on Streetcode Publish and Draft
  src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
Labels: bug

#332 Created validation for Url, fixed problem with photos
  src/features/AdminPage/NewsPage/News.component.tsx
  src/features/AdminPage/NewsPage/NewsModal/NewsModal.component.tsx
Labels: enhancement

#336 Developer master pagination buttons valerii
  src/features/AdminPage/StreetcodesTable/StreetcodesTable.component.tsx
Labels: enhancement

#339 fully completed instagram API
  src/app/api/instagram/instagram.api.ts
  src/features/MainPage/InstagramBlock/InstagramBlock.component.tsx
  src/features/MainPage/InstagramBlock/InstagramSliderItem/InstagramPost.model.ts
  src/features/MainPage/InstagramBlock/InstagramSliderItem/InstagramSliderItem.component.tsx
  src/models/instagram/instagram.model.ts
Labels: enhancement

#338 Fixed code related with mobx
  src/features/AdminPage/ForFansPage/ForFansPage/SourceItem.tsx
  src/features/AdminPage/NewsPage/News.component.tsx
Labels: enhancement

#341 remove protected from dictianary route
  src/app/router/Routes.tsx
Labels: bug
