Repository ita-social-projects/StreetCode_Client, pull requests merged in 2023-01, with the labels that each got.

#17 Fixed two major bugs related to media query mixin and hook.
  src/app/common/hooks/external/useMediaQuery.hook.ts
  src/assets/sass/_utils.functions.scss
  src/assets/sass/mixins/_media.mixins.scss
  src/assets/sass/mixins/_vendor.mixins.scss
Labels: bug

#19 Merge/related figure to master
  src/assets/images/Antonovich.png
  src/assets/images/Khmelnytsky.png
  src/assets/images/Mazepa.png
  src/assets/images/Ratushny.png
  src/assets/images/Ukrainka.png
  src/components/StreetcodeComponent/Streetcode.component.tsx
  src/features/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.styles.scss
  src/features/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.tsx
  src/features/RelatedFiguresBlock/RelatedFigures.component.tsx
  src/features/RelatedFiguresBlock/RelatedFigures.styles.scss
  src/features/SlickSlider/SliderItems/InterestingFactSliderItem/InterestingFactSliderItem.styles.scss
  src/models/additional-content/tag.model.ts
  src/models/media/image.model.ts
  src/models/streetcode/related-figure.model.ts
Labels: enhancement

#27 fix block representation for less then 4 elements
  src/features/RelatedFiguresBlock/RelatedFigures.component.tsx
  src/features/RelatedFiguresBlock/RelatedFigures.styles.scss
Labels: bug

#30 Added scroll-state observing hooks and adjusted global overflow styling.
  src/app/common/hooks/scrolling/useScrollDirection.hook.ts
  src/app/common/hooks/scrolling/useScrollPosition/useScrollPosition.d.ts
  src/app/common/hooks/scrolling/useScrollPosition/useScrollPosition.hook.ts
  src/app/common/hooks/scrolling/useScrollPosition/useScrollPosition.utils.ts
  src/components/StreetcodeComponent/Streetcode.component.tsx
  src/components/StreetcodeComponent/Streetcode.styles.scss
  src/index.scss
Labels: bug, enhancement

#31 fixed background and added hovers
  src/features/MainBlock/MainBlock.component.tsx
  src/features/MainBlock/MainBlock.styles.scss
Labels: bug, enhancement

#33 fixed text and added hovers for footer
  src/app/layout/footer/Footer.component.tsx
  src/app/layout/footer/Footer.styles.scss
  src/features/TextBlock/ReadMore/ReadMore.component.tsx
  src/features/TextBlock/ReadMore/ReadMore.styles.scss
Labels: bug

#37 Feat/add mobx
  src/app/api/agent.api.ts
  src/app/api/facts.api.ts
  src/app/api/media/arts.api.ts
  src/app/api/media/audios.api.ts
  src/app/api/media/images.api.ts
  src/app/api/media/videos.api.ts
  src/app/api/partners.api.ts
  src/app/api/streetcodes.api.ts
  src/app/api/subtitles.api.ts
  src/app/api/tags.api.ts
  src/app/api/terms.api.ts
  src/app/api/texts.api.ts
  src/app/api/timeline.api.ts
  src/app/api/toponyms.api.ts
  src/app/api/transactLinks.api.ts
  src/app/common/components/modals/InterestingFacts/InterestingFactsModal.component.tsx
  src/app/common/components/modals/Sources/SourcesModal.component.tsx
  src/app/common/contants/api-routes.constants.ts
  src/app/layout/app/App.tsx
  src/app/stores/art-store.ts
  src/app/stores/audio-store.ts
  src/app/stores/facts-store.ts
  src/app/stores/image-store.ts
  src/app/stores/interesting-facts-store.ts
  src/app/stores/local-storages/AuthLocalStorage.ts
  src/app/stores/modal-store.ts
  src/app/stores/partners-store.ts
  src/app/stores/root-store.ts
  src/app/stores/sources-store.ts
  src/app/stores/streetcode-store.ts
  src/app/stores/subtitles-store.ts
  src/app/stores/tags-store.ts
  src/app/stores/term-store.ts
  src/app/stores/text-store.ts
  src/app/stores/timelineitem-store.ts
  src/app/stores/toponym-store.ts
  src/app/stores/transactions-store.ts
  src/app/stores/videos-store.ts
  src/assets/images/utils/Cancel_btn.svg
  src/components/InterestingFacts/InterestingFacts.component.tsx
  src/features/SlickSlider/SliderItems/InterestingFactSliderItem/InterestingFactSliderItem.tsx
  src/features/SourcesBlock/SourceItem/SourceItem.component.tsx
  src/models/additional-content/coordinates.model.ts
  src/models/additional-content/subtitles.model.ts
  src/models/map/map.model.ts
  src/models/media/art.model.ts
  src/models/media/audio.model.ts
  src/models/media/video.model.ts
  src/models/partners/partners.model.ts
  src/models/sources/source-links.model.ts
  src/models/streetcode/streetcode-types.model.ts
  src/models/streetcode/text-contents.model.ts
  src/models/timeline/timeline-item.model.ts
  src/models/toponyms/toponym.model.ts
  src/models/transactions/transaction-link.model.ts
Labels: enhancement

#44 added api connection and fixed code smells
  src/app/common/components/TagList/TagList.component.tsx
  src/app/common/constants/api-routes.constants.ts
  src/app/common/utils/formatters.utils.ts
  src/app/layout/header/HeaderBlock.component.tsx
  src/features/StreetcodePage/MainBlock/BreadCrumb/BreadCrumb.component.tsx
  src/features/StreetcodePage/MainBlock/MainBlock.component.tsx
  src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx
  src/models/streetcode/streetcode-types.model.ts
Labels: enhancement

#43 Enh/sources api sync
  src/app/api/sources/sources.api.ts
  src/app/common/components/modals/InterestingFacts/InterestingFactsModal.component.tsx
  src/app/common/components/modals/Sources/SourcesModal.component.tsx
  src/app/common/components/modals/Sources/SourcesModal.styles.scss
  src/app/common/constants/api-routes.constants.ts
  src/app/common/hooks/stateful/useRouter.hook.ts
  src/app/layout/app/App.tsx
  src/app/stores/modal-store.ts
  src/app/stores/root-store.ts
  src/app/stores/sources-store.ts
  src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.component.tsx
  src/features/StreetcodePage/SourcesBlock/SourceItem/SourceItem.component.tsx
  src/features/StreetcodePage/SourcesBlock/Sources.component.tsx
  src/features/StreetcodePage/SourcesBlock/Sources.styles.scss
  src/models/sources/source-links.model.ts
  src/models/sources/sources.model.ts
  src/models/streetcode/streetcode-types.model.ts
Labels: enhancement

#51 Feat/audio player
  src/app/common/components/AudioPlayer/AudioPlayer.component.tsx
  src/app/common/components/AudioPlayer/AudioPlayer.styles.scss
  src/app/common/components/modals/ListenText/ListenText.component.tsx
  src/app/common/components/modals/ListenText/ListenText.styles.scss
  src/assets/images/audio-player/ExitBtn.png
  src/assets/images/audio-player/PauseBtn.png
  src/assets/images/audio-player/PlayBtn.png
  src/features/StreetcodePage/MainBlock/MainBlock.component.tsx
  src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx
Labels: enhancement

#53 Feet/sync back with related figures
  src/app/api/streetcode/related-figure.api.ts
  src/app/common/components/modals/RelatedFigures/RelatedFiguresModal.component.tsx
  src/app/common/components/modals/RelatedFigures/RelatedFiguresModal.styles.scss
  src/app/common/constants/api-routes.constants.ts
  src/app/layout/ModalWrapper.component.tsx
  src/app/stores/image-store.ts
  src/app/stores/modal-store.ts
  src/app/stores/related-figures-store.ts
  src/app/stores/root-store.ts
  src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.component.tsx
  src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.styles.scss
  src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.tsx
  src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigures.component.tsx
  src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigures.styles.scss
  src/models/streetcode/related-figure.model.ts
Labels: bug, enhancement

#59 Added requested header layout.
  package.json
  src/app/common/components/modals/HeaderLogin/HeaderLoginModal.component.tsx
  src/app/common/components/modals/HeaderLogin/HeaderLoginModal.styles.scss
  src/app/common/hooks/external/useEventListener.hook.ts
  src/app/common/hooks/stateful/useClickOutside.hook.ts
  src/app/layout/ModalWrapper.component.tsx
  src/app/layout/app/App.styles.scss
  src/app/layout/app/App.tsx
  src/app/layout/header/HeaderBlock.component.tsx
  src/app/layout/header/HeaderBlock.styles.scss
  src/app/layout/header/HeaderDrawer/HeaderDrawer.component.tsx
  src/app/layout/header/HeaderDrawer/HeaderDrawer.styles.scss
  src/app/layout/header/HeaderSkeleton/HeaderSkeleton.component.tsx
  src/app/layout/header/HeaderSkeleton/HeaderSkeleton.styles.scss
  src/app/layout/header/LanguageSelector/LanguageSelector.component.tsx
  src/app/layout/header/LanguageSelector/LanguageSelector.styles.scss
  src/app/stores/modal-store.ts
  src/features/StreetcodePage/Streetcode.component.tsx
  src/features/StreetcodePage/Streetcode.styles.scss
Labels: enhancement

#58 Added Scroll to top Btn.
  src/app/common/components/ScrollToTopBtn/ScrollToTopBtn.component.tsx
  src/app/common/components/ScrollToTopBtn/ScrollToTopBtn.styles.scss
  src/assets/images/utils/ScrollToTopBtn.svg
  src/features/StreetcodePage/Streetcode.component.tsx
Labels: enhancement

#61 Feat/page scrollbar
  package-lock.json
  package.json
  src/app/api/agent.api.ts
  src/app/common/hooks/external/useEventListener.hook.ts
  src/app/common/hooks/scrolling/useScrollPosition/useScrollPosition.hook.ts
  src/app/layout/app/App.component.tsx
  src/app/layout/app/App.styles.scss
  src/app/router/Routes.tsx
  src/assets/images/utils/ArrowUp.svg
  src/features/ProgressBar/NavigableBlockWrapper.component.tsx
  src/features/ProgressBar/ProgressBar.component.tsx
  src/features/ProgressBar/ProgressBar.styles.scss
  src/features/ProgressBar/ProgressBarFill/ProgressBarFill.component.tsx
  src/features/ProgressBar/ProgressBarFill/ProgressBarFill.styles.scss
  src/features/ProgressBar/ProgressBarSection/ProgressBarSection.component.tsx
  src/features/ProgressBar/ProgressBarSection/ProgressBarSection.styles.scss
  src/features/StreetcodePage/HeadingBlock/BlockHeading.component.tsx
  src/features/StreetcodePage/HeadingBlock/BlockHeading.styles.scss
  src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.component.tsx
  src/features/StreetcodePage/MainBlock/MainBlock.component.tsx
  src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.component.tsx
  src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigures.component.tsx
  src/features/StreetcodePage/SourcesBlock/Sources.component.tsx
  src/features/StreetcodePage/Streetcode.component.tsx
  src/features/StreetcodePage/TextBlock/TextBlock.component.tsx
  src/features/StreetcodePage/TextBlock/TextBlock.styles.scss
  src/features/StreetcodePage/TickerBlock/Ticker.styles.scss
  src/index.scss
Labels: enhancement

#60 Fix/styles
  src/app/common/components/ScrollToTopBtn/ScrollToTopBtn.component.tsx
  src/app/common/components/ScrollToTopBtn/ScrollToTopBtn.styles.scss
  src/app/common/hooks/scrolling/useScrollPosition/useScrollPosition.hook.ts
  src/app/layout/app/App.styles.scss
  src/app/layout/header/HeaderBlock.styles.scss
  src/assets/images/header/Streetcode_title.svg
  src/assets/images/utils/ScrollToTopBtn.svg
  src/assets/sass/variables/_variables.colors.scss
  src/features/StreetcodePage/DonateBtn/DonateBtn.component.tsx
  src/features/StreetcodePage/DonateBtn/DonateBtn.styles.scss
  src/features/StreetcodePage/TickerBlock/Ticker.styles.scss
Labels: bug, enhancement

#62 Fix/related figures
  src/app/api/additional-content/tags.api.ts
  src/app/api/streetcode/related-figure.api.ts
  src/app/common/components/modals/RelatedFigures/RelatedFiguresModal.component.tsx
  src/app/common/components/modals/RelatedFigures/RelatedFiguresModal.styles.scss
  src/app/common/components/modals/Sources/SourcesModal.component.tsx
  src/app/common/components/modals/Sources/SourcesModal.styles.scss
  src/app/common/constants/api-routes.constants.ts
  src/app/stores/modal-store.ts
  src/app/stores/related-figures-store.ts
  src/app/stores/tags-store.ts
  src/assets/images/utils/ModalBg.png
  src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.component.tsx
  src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.styles.scss
  src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigures.component.tsx
  src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigures.styles.scss
  src/features/StreetcodePage/SourcesBlock/Sources.component.tsx
  src/features/StreetcodePage/Streetcode.component.tsx
  src/features/StreetcodePage/TickerBlock/Ticker.component.tsx
  src/models/streetcode/related-figure.model.ts
Labels: enhancement

#63 added audio back-end connection
  src/app/api/media/audios.api.ts
  src/app/common/components/AudioPlayer/AudioPlayer.component.tsx
  src/app/common/constants/api-routes.constants.ts
  src/app/stores/audio-store.ts
  src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx
  src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.styles.scss
Labels: enhancement

#65 Fix/progress bar
  .gitignore
  src/app/common/components/modals/RelatedFigures/RelatedFiguresModal.styles.scss
  src/app/layout/header/HeaderBlock.component.tsx
  src/features/ProgressBar/ProgressBar.component.tsx
  src/features/ProgressBar/ProgressBar.styles.scss
  src/features/ProgressBar/ProgressBarSection/ProgressBarSection.component.tsx
  src/features/ProgressBar/ProgressBarSection/ProgressBarSection.styles.scss
  src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.component.tsx
  src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.styles.scss
  src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigures.component.tsx
  src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigures.styles.scss
  src/features/StreetcodePage/SourcesBlock/Sources.styles.scss
Labels: bug, enhancement

#68 fix modal
  src/app/common/components/modals/RelatedFigures/RelatedFiguresModal.styles.scss
  src/app/stores/related-figures-store.ts
  src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.component.tsx
  src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.styles.scss
  src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigures.component.tsx
  src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigures.styles.scss
Labels: bug, enhancement

#70 Enh/map block implementation
  package-lock.json
  package.json
  src/app/api/additional-content/streetcode-cooridnates.api.ts
  src/app/api/map/toponyms.api.ts
  src/app/common/constants/api-routes.constants.ts
  src/app/stores/checkbox-store.ts
  src/app/stores/root-store.ts
  src/assets/images/utils/Instagram.png
  src/features/StreetcodePage/MapBlock/CheckBox/CheckBox.component.tsx
  src/features/StreetcodePage/MapBlock/CheckBox/CheckBox.styles.scss
  src/features/StreetcodePage/MapBlock/Map/Map.component.tsx
  src/features/StreetcodePage/MapBlock/Map/Map.styles.scss
  src/features/StreetcodePage/MapBlock/Map/Marker/Marker.styles.scss
  src/features/StreetcodePage/MapBlock/Map/Marker/MarkerWrapper.component.tsx
  src/features/StreetcodePage/MapBlock/Map/MarkerCluster/MarkerCluster.styles.scss
  src/features/StreetcodePage/MapBlock/Map/MarkerCluster/MarkerClusterWrapper.component.tsx
  src/features/StreetcodePage/MapBlock/MapBlock.component.tsx
  src/features/StreetcodePage/MapBlock/MapBlock.styles.scss
  src/features/StreetcodePage/MapBlock/Statistics/Statistics.component.tsx
  src/features/StreetcodePage/MapBlock/Statistics/Statistics.styles.scss
  src/features/StreetcodePage/Streetcode.component.tsx
  src/models/additional-content/coordinate.model.ts
  src/models/toponyms/toponym.model.ts
Labels: enhancement

#69 Fix/partners
  src/app/api/partners/partners.api.ts
  src/app/common/constants/api-routes.constants.ts
  src/app/stores/partners-store.ts
  src/features/StreetcodePage/PartnersBlock/PartnerItem/PartnerContent/PartnerContent.component.tsx
  src/features/StreetcodePage/PartnersBlock/PartnerItem/PartnerContent/PartnerContent.styles.scss
  src/features/StreetcodePage/PartnersBlock/PartnerItem/PartnerItem.component.tsx
  src/features/StreetcodePage/PartnersBlock/PartnerItem/PartnerItem.styles.scss
  src/features/StreetcodePage/PartnersBlock/Partners.component.tsx
  src/models/partners/partners.model.ts
Labels: bug, enhancement

#72 Feat/timeline block
  package-lock.json
  package.json
  src/app/api/timeline/timeline.api.ts
  src/app/common/components/ScrollToTopBtn/ScrollToTopBtn.styles.scss
  src/app/common/constants/api-routes.constants.ts
  src/app/stores/root-store.ts
  src/app/stores/timeline-store.ts
  src/assets/images/timeline/Lviv.png
  src/assets/images/timeline/Square.png
  src/features/ProgressBar/ProgressBar.styles.scss
  src/features/SlickSlider/SlickSlider.component.tsx
  src/features/SlickSlider/index.ts
  src/features/StreetcodePage/DonateBtn/DonateBtn.styles.scss
  src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.component.tsx
  src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.component.tsx
  src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx
  src/features/StreetcodePage/PartnersBlock/PartnerItem/PartnerContent/PartnerContent.component.tsx
  src/features/StreetcodePage/PartnersBlock/Partners.component.tsx
  src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigures.component.tsx
  src/features/StreetcodePage/SourcesBlock/Sources.component.tsx
  src/features/StreetcodePage/Streetcode.component.tsx
  src/features/StreetcodePage/TimelineBlock/TimelineBlock.component.tsx
  src/features/StreetcodePage/TimelineBlock/TimelineBlock.styles.scss
  src/features/StreetcodePage/TimelineBlock/TimelineItem/TimelineItem.component.tsx
  src/features/StreetcodePage/TimelineBlock/TimelineItem/TimelineItem.styles.scss
  src/features/StreetcodePage/TimelineBlock/TimelineReelOutline/TimelineReelOutline.component.tsx
  src/features/StreetcodePage/TimelineBlock/TimelineReelOutline/TimelineReelOutline.styles.scss
  src/features/StreetcodePage/TimelineBlock/TimelineSlider.component.tsx
  src/features/StreetcodePage/TimelineBlock/TimelineSwiper/TimelineSwiper.component.tsx
  src/features/StreetcodePage/TimelineBlock/TimelineSwiper/TimelineSwiper.styles.scss
  src/features/StreetcodePage/TimelineBlock/TimelineSwiper/TimelineSwiperEdgeBtn/TimelineSwiperEdgeBtn.component.tsx
  src/features/StreetcodePage/TimelineBlock/TimelineSwiper/TimelineSwiperEdgeBtn/TimelineSwiperEdgeBtn.styles.scss
  src/features/StreetcodePage/TimelineBlock/Timespan/Timespan.component.tsx
  src/features/StreetcodePage/TimelineBlock/Timespan/Timespan.styles.scss
  src/models/timeline/chronology.model.ts
Labels: bug

#74 Fix/timeline tick swiper
  src/app/stores/timeline-store.ts
  src/features/StreetcodePage/TimelineBlock/TimelineBlock.component.tsx
  src/features/StreetcodePage/TimelineBlock/TimelineSlider.component.tsx
  src/features/StreetcodePage/TimelineBlock/TimelineSwiper/TimelineSwiper.component.tsx
  src/features/StreetcodePage/TimelineBlock/TimelineSwiper/TimelineSwiperEdgeBtn/TimelineSwiperEdgeBtn.component.tsx
Labels: bug

#73 Fix/donate btn
  src/app/common/components/BurgerMenu/BurgerMenu.styles.scss
  src/app/common/components/ScrollToTopBtn/ScrollToTopBtn.styles.scss
  src/app/common/components/modals/Donates/DonatesModal.component.tsx
  src/app/common/components/modals/Donates/DonatesModal.styles.scss
  src/app/layout/app/App.component.tsx
  src/app/layout/app/App.styles.scss
  src/app/layout/header/HeaderBlock.component.tsx
  src/app/layout/header/HeaderBlock.styles.scss
  src/app/layout/header/HeaderDrawer/HeaderDrawer.component.tsx
  src/app/layout/header/HeaderSkeleton/HeaderSkeleton.component.tsx
  src/features/ProgressBar/ProgressBar.component.tsx
  src/features/ProgressBar/ProgressBar.styles.scss
  src/features/StreetcodePage/DonateBtn/DonateBtn.component.tsx
  src/features/StreetcodePage/DonateBtn/DonateBtn.styles.scss
Labels: bug, enhancement
