Repository ita-social-projects/StreetCode_Client, pull requests merged in 2023-10, with the labels that each got.

#837 add links for vacancies` description
  src/app/common/constants/email.constants.ts
  src/features/AboutUsPage/Vacancies/Vacancy/Vacancy.component.tsx
  src/features/AboutUsPage/Vacancies/Vacancy/Vacancy.syles.scss
  src/features/AboutUsPage/Vacancies/Vacancy/VacancyModal/VacancyModal.component.tsx
  src/features/AdditionalPages/ContactUsPage/MainBlock/ContactBlock/ContactBlock.component.tsx
  src/features/AdditionalPages/PrivatePolicyPage/SubSections/SubSectionFifth/SectionFifth.component.tsx
  src/features/AdditionalPages/PrivatePolicyPage/SubSections/SubSectionSeventh/SectionSeventh.component.tsx
  src/features/AdminPage/JobsPage/JobsModal/JobsModal.component.tsx
Labels: bug

#846 add possibility to navigate with clicking on options
  src/features/AboutUsPage/TeamMembers/TeamPositionsSlider/TeamPositionSlider.styles.scss
  src/features/AboutUsPage/TeamMembers/TeamPositionsSlider/TeamPostionSlider.component.tsx
Labels: small

#857 try N2 to fix news overflow (change to absolute "До новини" btn)
  src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.styles.scss
Labels: bug, small

#863 block heading fixed
  src/features/StreetcodePage/HeadingBlock/BlockHeading.component.tsx
  src/features/StreetcodePage/HeadingBlock/BlockHeading.styles.scss
  src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.styles.scss
Labels: styles

#875 add possibility to navigate by clicking on facts
  src/features/SlickSlider/InterestingFactSliderSlickSlider.component.tsx
  src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.component.tsx
  src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.component.tsx
  src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.styles.scss
  src/features/StreetcodePage/SourcesBlock/Sources.component.tsx
Labels: bug, small

#874 Fixed unavailabilbity of previous categories in for fans admin modal
  src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx
Labels: bug

#888 fix slider
  src/features/StreetcodePage/SourcesBlock/SourceItem/SourceItem.component.tsx
Labels: bug

#889 delete gif in qr block
  src/features/StreetcodePage/QRBlock/QRMobile/QRMobile.component.tsx
  src/features/StreetcodePage/QRBlock/QRMobile/QRMobile.styles.scss
Labels: small

#894 Dashes and font fix
  src/app/common/components/ContactForm/ContactForm.component.tsx
  src/app/common/components/modals/Partners/PartnersModal.component.tsx
  src/features/AdditionalPages/PartnersPage/Title/Title.component.tsx
  src/features/AdditionalPages/PartnersPage/Title/Title.styles.scss
Labels: bug

#892 Fixed fonts, indentations, flex gap in survey modal
  src/app/common/components/modals/Survey/SurveyModal.component.tsx
  src/app/common/components/modals/Survey/SurveyModal.styles.scss
Labels: styles

#893 Sort news by date in admin panel
  src/app/stores/news-store.ts
  src/features/AdminPage/NewsPage/News.component.tsx
Labels: bug, enhancement

#890 Feature/added new links for team members
  src/assets/images/partners/behance.svg
  src/assets/images/partners/facebook.svg
  src/assets/images/partners/facebook.webp
  src/assets/images/partners/https.svg
  src/assets/images/partners/instagram.svg
  src/assets/images/partners/instagram.webp
  src/assets/images/partners/linkedin.svg
  src/assets/images/partners/tiktok.svg
  src/assets/images/partners/twitter.webp
  src/assets/images/partners/twitterNew.svg
  src/assets/images/partners/youtube.svg
  src/assets/images/partners/youtube.webp
  src/features/AboutUsPage/TeamMemberCard/TeamMemberLinks/TeamMemberLinks.component.tsx
  src/features/AdminPage/PartnersPage/PartnerLink.component.tsx
  src/features/AdminPage/PartnersPage/Partners.component.tsx
  src/features/AdminPage/TeamPage/TeamLink.component.tsx
  src/features/AdminPage/TeamPage/TeamModal/TeamModal.component.tsx
  src/features/AdminPage/TeamPage/TeamPage.component.tsx
  src/features/MainPage/TeamSlider/TeamItemSlider/TeamItemSlider.component.tsx
  src/features/StreetcodePage/PartnersBlock/PartnerItem/PartnerContent/PartnerContent.component.tsx
  src/models/team/team.model.ts
Labels: enhancement

#896 Sort source categories by name in Admin panel
  src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx
Labels: enhancement

#915 main-page-team-fix
  src/features/MainPage/TeamSlider/TeamItemSlider/TeamItemSlider.component.tsx
Labels: bug

#886 fix vacancies modal
  src/features/AdminPage/JobsPage/JobsModal/JobsModal.component.tsx
  src/features/AdminPage/JobsPage/JobsModal/JobsModal.styles.scss
Labels: bug, small

#901 joinTheTeamBtn_fix: fix button click
  src/app/common/components/modals/HeaderLogin/HeaderLoginModal.component.tsx
  src/app/common/components/modals/HeaderLogin/HeaderLoginModal.styles.scss
Labels: bug

#902 Fixed donates checkbox styles in modal
  src/app/common/components/modals/Donates/DonatesModal.styles.scss
Labels: styles

#906 Partners fonts fix
  src/features/AdditionalPages/PartnersPage/Partners.styles.scss
  src/features/AdditionalPages/PartnersPage/Title/Title.styles.scss
Labels: bug

#907 add possibility to redirect to news with click
  src/features/MainPage/NewsSlider/NewsSlider.component.tsx
  src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.component.tsx
  src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.styles.scss
Labels: small

#910 The correct display of the sun icon in the Streetcode catalog has been fixed
  src/features/StreetcodeCatalogPage/StreetcodeCatalog.component.tsx
Labels: bug

#930 Changed all social media icons + minor fixes
  src/app/common/constants/social.constants.ts
  src/app/layout/footer/Footer.component.tsx
  src/app/layout/footer/Footer.styles.scss
  src/app/layout/header/HeaderDrawer/SocialMediaLinks/SocialMediaLinks.component.tsx
  src/assets/images/contact-us/Email.svg
  src/assets/images/contact-us/Facebook.svg
  src/assets/images/contact-us/Facebook.webp
  src/assets/images/contact-us/Instagram.svg
  src/assets/images/contact-us/Instagram.webp
  src/assets/images/contact-us/Telegram.svg
  src/assets/images/contact-us/TikTok.svg
  src/assets/images/contact-us/TikTok.webp
  src/assets/images/contact-us/Twitter.svg
  src/assets/images/contact-us/Twitter.webp
  src/assets/images/contact-us/YouTube.svg
  src/assets/images/contact-us/Youtube.webp
  src/assets/images/contact-us/email.webp
  src/assets/images/footer/Facebook.svg
  src/assets/images/footer/Facebook.webp
  src/assets/images/footer/Instagram.svg
  src/assets/images/footer/Instagram.webp
  src/assets/images/footer/Telegram.svg
  src/assets/images/footer/TikTok.webp
  src/assets/images/footer/Tiktok.svg
  src/assets/images/footer/Twitter.webp
  src/assets/images/footer/Twitter2.svg
  src/assets/images/footer/Youtube.svg
  src/assets/images/footer/Youtube.webp
  src/assets/images/header-drawer/Facebook.svg
  src/assets/images/header-drawer/Facebook.webp
  src/assets/images/header-drawer/Instagram.svg
  src/assets/images/header-drawer/Instagram.webp
  src/assets/images/header-drawer/Telegram.svg
  src/assets/images/header-drawer/TikTok.webp
  src/assets/images/header-drawer/Tiktok.svg
  src/assets/images/header-drawer/Twitter.webp
  src/assets/images/header-drawer/Youtube.svg
  src/assets/images/header-drawer/Youtube.webp
  src/features/AboutUsPage/AboutUsHeaderText/AboutUsHeaderText.component.tsx
  src/features/AboutUsPage/Founders/Founder/FounderCard/FounderCard.component.tsx
  src/features/AboutUsPage/Founders/Founder/FounderCard/FounderCard.styles.scss
  src/features/AboutUsPage/Founders/Founders.component.tsx
  src/features/AdditionalPages/ContactUsPage/MainBlock/ContactBlock/ContactBlock.component.tsx
  src/features/AdditionalPages/ContactUsPage/MainBlock/ContactBlock/ContactBlock.styles.scss
Labels: enhancement, styles

#914 added blur to the top of the teaser block on streetcode page
  src/assets/sass/mixins/_utils.mixins.scss
  src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx
  src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.styles.scss
Labels: styles

#917 Fixed indentations and other minor styles
  src/features/MainPage/Heading/Heading.styles.scss
  src/features/MainPage/InstagramBlock/InstagramBlock.styles.scss
  src/features/MainPage/NewsSlider/NewsSlider.styles.scss
  src/features/MainPage/PartnersBlockMain/PartnersBlockMain.styles.scss
  src/features/MainPage/TeamSlider/TeamComponent.styles.scss
  src/features/MainPage/TeamSlider/TeamItemSlider/TeamItemSlider.styles.scss
Labels: styles

#936 Privace policy space fix
  src/features/AdditionalPages/PrivatePolicyPage/SubSections/SubSectionSeventh/SectionSeventh.component.tsx
Labels: bug

#928 Loading "sun" works in a right way in catalog page
  src/app/stores/streetcodes-catalog-store.ts
  src/features/StreetcodeCatalogPage/StreetcodeCatalog.component.tsx
Labels: bug, invalid

#939 added limit for news text
  src/features/AdminPage/NewsPage/NewsModal/NewsModal.component.tsx
Labels: enhancement

#940 Burger menu slider dot fix
  src/app/layout/header/HeaderDrawer/HeaderDrawer.component.tsx
  src/app/layout/header/HeaderDrawer/HeaderDrawer.styles.scss
Labels: bug

#942 Fixed the navigation of tags slider by keyboard arrows
  src/app/common/components/modals/Tags/TagsSliderModal/TagsSliderModal.component.tsx
Labels: bug

#944 Tags clickable space area fix
  src/app/common/components/modals/Tags/TagsSliderModal/TagsSliderModal.styles.scss
Labels: bug

#947 Fixed mobile streetcodes catalog to display 2 streetcode cards per row
  src/features/StreetcodeCatalogPage/StreetcodeCatalog.styles.scss
Labels: bug, styles

#952 Links to third-party resources open in a new tab
  src/app/common/components/modals/Donates/DonatesModal.component.tsx
  src/features/AboutUsPage/Founders/Founder/FounderCard/FounderCard.component.tsx
  src/features/AboutUsPage/Founders/Founders.component.tsx
  src/features/AboutUsPage/TeamMemberCard/TeamMemberLinks/TeamMemberLinks.component.tsx
  src/features/AdditionalPages/SupportUsPage/SupportUs.component.tsx
  src/features/AdditionalPages/SupportUsPage/components/DonationBlock.component.tsx
  src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx
  src/features/StreetcodePage/SourcesBlock/SourceItem/SourceItem.component.tsx
  src/features/StreetcodePage/SourcesBlock/Sources.component.tsx
  src/features/StreetcodePage/TextBlock/TextBlock.component.tsx
Labels: bug

#963 Add paddings to partners img
  src/features/AdditionalPages/PartnersPage/PartnersItem/PartnersItem.styles.scss
Labels: styles, small

#966 Fixed vertical progress bar scrolling on mouse clicking
  src/features/ProgressBar/ProgressBar.component.tsx
Labels: bug
