Repository ita-social-projects/StreetCode_Client, pull requests merged in 2024-03, with the labels that each got.

#1173 Fix bug #1178
  package-lock.json
  package.json
  src/features/StreetcodePage/DonateBtn/DonateBtn.component.tsx
  src/features/StreetcodePage/Streetcode.component.tsx
  yarn.lock
Labels: bug

#1164 Fix bug #964
  public/index.html
Labels: bug, small

#1184 Fix bug issue #950
  src/app/common/components/CardText/CardText.component.tsx
  src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.component.tsx
  src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.styles.scss
  src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.styles.scss
Labels: bug

#1209 fixed issue-958
  src/app/common/components/modals/ConfirmationModal/ConfirmationModal.component.tsx
Labels: small

#1166 Change width in modal window to 340px
  src/app/common/components/modals/InterestingFacts/InterestingFactsModal.styles.scss
Labels: styles, small
